### ISSUE TITLE
Compatibility with RN Modal

### ISSUE THREAD

**Issue by Xyzor** [lucasferreira/react-native-flash-message#1]
Hello!

I'm curious if it's possible to show the message bar on top of an open [modal component](https://facebook.github.io/react-native/docs/modal.html)?

**Comment by lucasferreira** [comment]
Hi @Xyzor,

That's a good question! The native modal it's a native view, with yours own render properties inclusive with hardware acceleration possibilities in android. So, for now I recommend to use flash message inside native modals inside the modal, as local ref mode.

I've made this Snack to demo what I recommend: https://snack.expo.io/@lucasferreira/flash-message-modal-demo

What do you think?

**Comment by Xyzor** [comment]
It crashes every time I try to start the app. Both on device and preview

**Comment by lucasferreira** [comment]
Hi @Xyzor 

Are you testing in Expo app?

If you look here you can see that works: https://snack.expo.io/@lucasferreira/flash-message-modal-demo

(use the embed simulator in the right sidebar).

Also, in your project don't forget tu run `npm install react-native-flash-message`

**Comment by rahmanharoon** [comment]
> Hi @Xyzor
> 
> Are you testing in Expo app?
> 
> If you look here you can see that works: https://snack.expo.io/@lucasferreira/flash-message-modal-demo
> 
> (use the embed simulator in the right sidebar).
> 
> Also, in your project don't forget tu run `npm install react-native-flash-message`

How can i acheive this in functional component
