### ISSUE TITLE
Description not visible in showMessage

### ISSUE THREAD

**Issue by rakeshpalivela** [lucasferreira/react-native-flash-message#101]
When I execute below code the description was not appearing. It only displaying the message on flash.

showMessage({
  message: "Hello World",
  description: "This is our second message",
  type: "success",
});

I able to see only message "Hello World"

**Comment by lucasferreira** [comment]
Hi @rakeshpalivela,

I've made a basic demo ate Expo, could you test what happening? https://snack.expo.io/o!qyLqx6w

Here in my tests are everything normal...

**Comment by rakeshpalivela** [comment]
Hi @lucasferreira I have tried this earlier, its working fine here. In my project its not working.
<FlashMessage /> what is this tag for? Why show message not working with out this tag?
