### ISSUE TITLE
Global Flash Message with createAppContainer

### ISSUE THREAD

**Issue by yoyo7373** [lucasferreira/react-native-flash-message#102]
Right now I have an issue with using the flash message globally with my stack navigator and app container, because I don't have a way to export the flash message with the app container since I'm using createAppContainer in order to comply with the newer version of react-navigation, does anyone know how I can still use it globally with the createAppContainer method?

**Comment by lucasferreira** [comment]
Hi @yoyo7373 

In other issue I've found this Snack: https://snack.expo.io/SJvZoEXkN

If you go down in to the code you will see the correct method to use `createAppContainer` and `FlashMessage`.
