### ISSUE TITLE
Message not respecting container padding when rendering icon

### ISSUE THREAD

**Issue by LaurelOlson** [lucasferreira/react-native-flash-message#103]
The message title and description extend outside of the flash message container when they reach a certain length. This only seems to be an issue when `icon` is passed to `showMessage`

To reproduce:

```
<FlashMessage
  position="top"
/>
```

```
showMessage({
  message: 'Messsage Title',
  description: 'really long message really long message really long message wow so long Message',
  type: 'info',
  icon: 'info', // << works if this is removed
})
```

I've fixed this by patching the package and amending the following style:

```
flashLabel: {
    flexDirection: "column",
    flex: 1, // << added this
},
```

not sure if this is the actual fix but working for me in case anyone else is experiencing this issue

**Comment by lucasferreira** [comment]
Hi @LaurelOlson thanks for this tip ;)

**Comment by deserthurricane** [comment]
Hello! 👋 
This issue still exists in master branch. Could you add the suggested style in the next version, please? It works. 👍
