### ISSUE TITLE
Flash message doesn't appear untill app restarts on some android devices.

### ISSUE THREAD

**Issue by hiteshAr** [lucasferreira/react-native-flash-message#111]
I do face the similar issue and the way i do is just like your second example @enigmablue  can you please help me how you solved it? This happens on some devices on other it works fine

_Originally posted by @Hiteshstack in https://github.com/lucasferreira/react-native-flash-message/issues/100#issuecomment-664990655_

**Comment by enigmablue** [comment]
Well actually i just placed my FlashMessage after my navigator (or stack navigators)

 ```
  <View style={{flex: 1}}>
              <NavigatorViewContainer />
               <FlashMessage />
    </View>
```

**Comment by erickhabil** [comment]
> I do face the similar issue and the way i do is just like your second example @enigmablue can you please help me how you solved it? This happens on some devices on other it works fine
> 
> _Originally posted by @hiteshStack in [#100 (comment)](https://github.com/lucasferreira/react-native-flash-message/issues/100#issuecomment-664990655)_

I hope that my code helps to you:

```
return (
      <AuthContext.Provider value={authContext}>
        <NavigationContainer>
          <FlashMessage
            floating={true}
            position={'top'}
            hideOnPress={true}
          />
          <StatusBarComponent
            backgroundColor={BACKGROUND_BLUE}
            translucent={true}
            statusBarFontStyle={'light-content'}
          />
          <ApolloProvider client={APOLLO_CLIENT}>

            {
              loginState.userToken == null ?
                <UnsignedUserNavigation />
                :
                <DrawerNavigation />
            }

          </ApolloProvider>
        </NavigationContainer>
      </AuthContext.Provider>
    );
```
