### ISSUE TITLE
Display flash message horizontally

### ISSUE THREAD

**Issue by hamonaco** [lucasferreira/react-native-flash-message#112]
Hi Lucas.
I was trying to display the flash message horizontally instead of vertically, I mean, display the message from left to right instead from the top of the screen. But I didn't found a way to do this in the current version. 
I already implemented the functionality and just adding an attribute "direction" you can switch between vertical and horizontal.

Are you able to accept a pull request ?

Thx -  Hugo Monaco.

**Comment by santiagopf** [comment]
@hamonaco Nice one, this will come in handy for my project

**Comment by hamonaco** [comment]
@santiagopf I hope it be helpful

Here is the PR #118
