### ISSUE TITLE
How can i add an ID to the flash message so i can select the element.

### ISSUE THREAD

**Issue by YahyaQandel** [lucasferreira/react-native-flash-message#113]

**Comment by hamonaco** [comment]
Hi. you could use a ref 

_**If you don't need a global use for (e.g. will use only in one screen) you can instance your FlashMessage Component with a ref ID (or other capture ref method):**_
`<FlashMessage ref="myLocalFlashMessage" />`

**Comment by Doaa-Ismael** [comment]
@hamonaco 
Hi, 
I want to set testID for message component for example, so I can use it in my e2e tests like this

```js
const errorMessage = await emulatorDriver.elementByAccessibilityId(id));
const errorMessageText = await errorMessage.text();
```

how to set this testID using ref?

**Comment by hamonaco** [comment]
Hi @Doaa-Ismael. I'm not sure if we can do that with ref property. I usualy use it to set the element ref into a variable to use it inside the component, for example:

```
class MyCustomComponent extends Component {
    let elementRef;

    render () {
        return (
            <FlashMessage ref="elementRef" />
        )
    }
}
```

This way yo can use the reference as a variable.

**Comment by lucasferreira** [comment]
Hi @YahyaQandel and @Doaa-Ismael 

Now it's possible to past `testID` in <FlashMessage />.

Thanks for this issue ;)
