### ISSUE TITLE
How do you customize colors globally

### ISSUE THREAD

**Issue by mozibrand** [lucasferreira/react-native-flash-message#12]
Define global colors. Don't define colors every time，How did you do it

**Comment by lucasferreira** [comment]
Hi @mozibrand 

Colors are defined here:
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L344

As a static variable in Component they are defined globally. You could customize globally using `setColorTheme` or when you call `showMessage` you could pass a custom background color or font color.

It's that your question?

**Comment by mozibrand** [comment]
Thank you for your answer, but I'm not quite sure how to do it, like, should I write it like this： 
showMessage({
                type: state,
                message: title,
                description:message,
                setColorTheme: {
                    success: "#25c879",
                    info: "#75a4f6",
                    warning: "#ff9398",
                    danger: "#d990fb",
                }
            });

It didn't work

**Comment by mozibrand** [comment]
Please tell me how it is implemented，thank you ver much

**Comment by lucasferreira** [comment]
You use something like that:

```jsx
import FlashMessage from "react-native-flash-message";

class App extends React.Component {
  componentDidMount() {
    FlashMessage.setColorTheme({
      success: "#25c879",
      info: "#75a4f6",
      warning: "#ff9398",
      danger: "#d990fb",
    });
  }
  render() {
   return <View />; // YOUR LAYOUT APP HERE
 }
}
```

`setColorTheme` it's a static method from FlashMessage component, you can call then in your top app structure like I did in the sample above.

So next time ahead in your code when you call `showMessage({ type: "success", message: title, description:message}` your message will be shown with color "#25c879".

Please try over there and feedback me if it works ;)

**Comment by mozibrand** [comment]
Thank you very much for your contribution，Is very perfect

**Comment by lucasferreira** [comment]
You're welcome ;)

**Comment by alexakasanjeev** [comment]
@lucasferreira Can I update Readme file, mentioning this static method, and how to change color, I mean, we don't have to look at source code or search issue, for this

I want to make two edits in README, can I contribute this?

1. Mention how to change color
2. Rename `Props` title to `FlashMessage component Props`(this will just remove ambiguity)

**Comment by lucasferreira** [comment]
Hi @alexakasanjeev,

Your PR will be very welcome ;)
