### ISSUE TITLE
Missing TypeScript definition for style

### ISSUE THREAD

**Issue by kickbk** [lucasferreira/react-native-flash-message#120]
This is a great lib. Thanks!
You're missing the `style` prop in `export interface MessageOptions` so it's giving an error

**Comment by kickbk** [comment]
Please update index.d.ts with 

```
export interface MessageOptions {
  ...
  style?: StyleProp<ViewStyle>;
}
```

**Comment by lucasferreira** [comment]
Hi @kickbk I think that's OK in our last version.
