### ISSUE TITLE
If I navigate to a different screen, will the banner still be visible?

### ISSUE THREAD

**Issue by oferRounds** [lucasferreira/react-native-flash-message#121]

**Comment by lucasferreira** [comment]
@oferRounds if you place the <FlashMessage /> above the navigator component, yes.

**Comment by oferRounds** [comment]
You mean the one of `react-navigation`? I use `react-native-navigation` - there is no such navigation component there. So i guess it wont work

**Comment by lucasferreira** [comment]
Hi @oferRounds you could follow this issue https://github.com/lucasferreira/react-native-flash-message/issues/34

**Comment by oferRounds** [comment]
@lucasferreira thank you for this reference! Did not use `react-native-flash-message` eventually, but was able to make it work thanks to your reference! Thank you!
