### ISSUE TITLE
Use ShowMessage in App.js

### ISSUE THREAD

**Issue by iampapagray** [lucasferreira/react-native-flash-message#123]
Thanks for this great library.

I need help in implementing this library for use in my App.js file. The reason being that I have a push notification listener inside of the App.js file and when the notification is received, I want to use this library to show the notification for the user.

However, I can't seem to do it even though everything works fine when I do ShowMessage({}) from another component;
Please help.

**Comment by rrrr4444** [comment]
Did you put the flash component in the main view?
