### ISSUE TITLE
in iPhone 12 series, height is too short

### ISSUE THREAD

**Issue by huurray** [lucasferreira/react-native-flash-message#126]
![Simulator Screen Shot - iPhone 12 Pro - 2020-10-28 at 23 15 44](https://user-images.githubusercontent.com/41982439/97448072-93690980-1973-11eb-99c8-a852145c0f5d.png)

like this style is not work properly.
only this error happen in iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max, not iPhone 12 mini.
please fix it for me.
thanks!

**Comment by lucasferreira** [comment]
Hi @huurray 

It's seems to be a problem with old `react-native-iphone-x-helper` package version.

Last version of our lib are updated, could please update the package and try again?

**Comment by huurray** [comment]
work well!!
thanks!!
