### ISSUE TITLE
Not showing message on iOS 14 

### ISSUE THREAD

**Issue by lukaspechar** [lucasferreira/react-native-flash-message#130]
I've tried numerous variations of the `showMessage` call however none of them render on iOS14. All works well on anything below that version of iOS. I've also updated to the latest version `0.1.17`. After some debugging it seems like the `componentDidMount` is not being called in the `FlashMessage.js` file on iOS 14. Any help would be appreciated. Thanks.

**Comment by TNBoiBoi** [comment]
Bump

**Comment by Cattari** [comment]
Facing the same issue, this forcing me to change the library

**Comment by Cattari** [comment]
I've fixed it by adding `canRegisterAsDefault` property to FlashMessage. Hope it will help you as well

**Comment by lucasferreira** [comment]
Hi @Cattari and others...

That's sound weird. If you need to set canRegisterAsDefault as true in FlashMessage instance at your root level it seams that iOS 14 and RN aren't work well with the `defaultProps` because this prop are true by default.

@TNBoiBoi and @lukaspechar could you try the @Cattari solution and give us some feedback?

**Comment by lucasferreira** [comment]
Hi @TNBoiBoi and  @lukaspechar

I just released a new version fixing other bugs. But with my sample expo app, in my iPhone XR running iOS 14 I could use flash message normally.

Can you update your install and test it again? If it keeps didn't work, could you pass more details to us?

**Comment by TNBoiBoi** [comment]
> Hi @TNBoiBoi and @lukaspechar
> 
> I just released a new version fixing other bugs. But with my sample expo app, in my iPhone XR running iOS 14 I could use flash message normally.
> 
> Can you update your install and test it again? If it keeps didn't work, could you pass more details to us?

Thanks a lot!! And thanks for the package :)
