### ISSUE TITLE
extend default renderFlashMessageIcon

### ISSUE THREAD

**Issue by thlmenezes** [lucasferreira/react-native-flash-message#131]
I'd like to write a custom method for rendering icons that extends the original, but I've had non-successful attempts to access the default method

I believe that the function could be accessed like this

```
import { renderFlashMessageIcon } from 'react-native-flash-message';
```

but it returns undefined

...help?

**Comment by lucasferreira** [comment]
Hi @thlmenezes 

I had forgotten to export this method in default package. Now in the latest version this is fixed:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/index.js#L20

Could you update your install and test it again?

**Comment by thlmenezes** [comment]
Hello @lucasferreira,

Sorry for the late feedback, I was on vacation from the project where I use this package; I've upgrade from version 0.1.16 to 0.1.22 and now the export is working as expected, I can now extend and modify the icons.

Thank you very much for your time and attention.
