### ISSUE TITLE
React 5.0 Issue

### ISSUE THREAD

**Issue by santhoshinet** [lucasferreira/react-native-flash-message#136]
Hi All, 

I am getting the below error once I install this package, please help how to resolve this

"Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).

The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals"

Thanks in advance

**Comment by lucasferreira** [comment]
Hi @santhoshinet 

It's just a warning about EXPO (not React), and isn't an error. You could use normally just ignore this.
