### ISSUE TITLE
Warning message while using with expo: global __expo will be deprecated in SDK 41

### ISSUE THREAD

**Issue by aadelgrossi** [lucasferreira/react-native-flash-message#137]
A warning is shown while using react-native-flash-message with Expo. Constants API is now located under expo-constants package and will be deprecated in upcoming SDK version. I am the latest SDK 40 right now.

https://user-images.githubusercontent.com/6358947/103587490-22d7ef00-4ec6-11eb-8272-200bc5e55e74.mp4

Logs:
```
Your project is accessing the following APIs from a deprecated global rather than a module import: Constants (expo-constants).
The global "__expo" and "Expo" objects will be removed in SDK 41. Learn more about how to fix this warning: https://expo.fyi/deprecated-globals
```

In FlashMessageWrapper.js, constants is accessed under the global object to obtain statusBarHeight.
```
if (isAndroid) {
    if (global.Expo) {
      return global.Expo.Constants.statusBarHeight + 6;
    } else {
      return 6;
    }
  }
```

**Comment by joaovbibiano** [comment]
Yes, I also notice that warning... I think it's important to see this
