### ISSUE TITLE
Unable to resolve module `@unimodules/core`

### ISSUE THREAD

**Issue by scaralfred** [lucasferreira/react-native-flash-message#139]
Getting this error as soon as I import the library.
Unable to resolve module `@unimodules/core` from `node_modules/expo-constants/build/Constants.js`: @unimodules/core could not be found within the project.

This happens with version 0.1.19

Instead with version 0.1.18 I get this:
undefined Unable to resolve module `expo-constants` from `node_modules/react-native-flash-message/src/FlashMessageWrapper.js`: expo-constants could not be found within the project.

**Comment by lucasferreira** [comment]
It's because this PR https://github.com/lucasferreira/react-native-flash-message/pull/138

But I will fix this in the next hours.

**Comment by lucasferreira** [comment]
Fixed in the last version `0.1.20` that already publish at npm.
