### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by hisankaran** [lucasferreira/react-native-flash-message#14]
Hi,
thanks for this awesome lib. I am wondering if there is a way to customize the fontFace when using a custom font throughout the app?

Thanks,

**Comment by lucasferreira** [comment]
Hi @hisankaran,

You could pass some `titleStyle` prop in your `showMessage` call, something like that:

`showMessage({ message: 'Hello', type: 'success', titleStyle: { fontWeight: 'bold', color: 'red', fontSize: 21, ... other font styles that you need } })`

**Comment by hisankaran** [comment]
Hi,

Thanks for the response. Is there a way to set this up globally?

Thanks!

**Comment by lucasferreira** [comment]
Hi @hisankaran 

It's not "oficial" but you could try in the root _FlashMessage_ declaration:

```<FlashMessage titleStyle={{ fontWeight: 'bold', ........... }} />```

But I really don't know if it will works well. Can you try it?

**Comment by maxbeech** [comment]
Can confirm this works great, thanks a lot @lucasferreira!

**Comment by lucasferreira** [comment]
Thanks for the feedback @maxbeech

**Comment by maxbeech** [comment]
No worries mate, cheers for the great module 💯
