### ISSUE TITLE
Rendering grey background with no text

### ISSUE THREAD

**Issue by alexakasanjeev** [lucasferreira/react-native-flash-message#144]
**Problem**
Hello, I have integrated the library and when the static method `showMessage` is called from screens that are registered in `Stack`, `Darwer`, `BottomTab` navigators, it is working fine, but when I call the static method `showMessage` from `AlertDIalog` screen which is present on `RootNavigator` in which screen will behave as [modal](https://reactnavigation.org/docs/modal) it is rendering a grey background with no Text is rendering

I have looked into other issues but couldn't find anything helpful

[Video of the problem](https://drive.google.com/file/d/14VfxZls9DaPkRXjPxlRElY57YpyIwdnJ/view?usp=sharing) - In video you can see that, when I show message after login it shows correctly, but when I show message at logout click, it is rendering gray background with no text

**App.js**

```jsx

const App = () => (
  <View>
      <RootNavigator />
      <FlashMessage hideStatusBar position="top" titleStyle={TYPOGRAPHY.flashMessageTitle} />
  </View>
);
```

**RootNavigator**

```jsx
const RootNavigator = () => {
  return (
    <SafeAreaProvider>
      <StatusBar
        barStyle={theme.appbar.barStyle}
        backgroundColor={theme.appbar.statusBarColor}
      />
      <NavigationContainer>
        <Stack.Navigator
          mode="modal"
          headerMode="none"
          screenOptions={{
            cardStyle: { backgroundColor: 'transparent' },
            cardOverlayEnabled: false,
          }}
        >
          <Stack.Screen name="modal" component={DrawerNavigator} />
          <Stack.Screen
            name={NAVIGATION_TO_ALERT_DIALOG}
            component={AlertDialog}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
};

const DrawerNavigator = () => (
  <Drawer.Navigator drawerContent={props => <DrawerScreen {...props} />}>
    <Drawer.Screen
      name="drawer"
      component={HomeStackNavigator}
      options={{
        swipeEnabled: false,
      }}
    />
  </Drawer.Navigator>
);

// Inside HomeStackNavigator there is again a Bottom Tab navigator
```

**Code in LogoutButton in Drawer**

```jsx
() => {
showMessage({
          description: translate('common.logoutSuccessMessage'),
          type: 'success',
        });
        navigation.navigate(NAVIGATION_TO_HOME_SCREEN, {
          screen: NAVIGATION_TO_HOME_SCREEN,
          params: {
            screen: NAVIGATION_TO_HOME_SCREEN,
          },
        });
}
```

![Screenshot_1612682805](https://user-images.githubusercontent.com/13250741/107140704-f5111a80-6949-11eb-9408-19fa97bbc543.png)

**Comment by lucasferreira** [comment]
Hi @alexakasanjeev,

Your text aren't shown because you are using `description` prop, please try `message` instead:

```showMessage({
          message: translate('common.logoutSuccessMessage'),
          type: 'success',
        });```

`DESCRIPTION` it's used only if you have two lines of message (title and description).

**Comment by alexakasanjeev** [comment]
Thank you @lucasferreira, that solved the problem
