### ISSUE TITLE
Not show message on real device iOS 14.3 #145

### ISSUE THREAD

**Issue by cenaHara** [lucasferreira/react-native-flash-message#146]
I've tried numerous variations of the showMessage call however none of them render on iOS14.3 it works well simulator
this is my code:

<img width="702" alt="Screen Shot 2021-03-01 at 13 27 18" src="https://user-images.githubusercontent.com/72627022/109459920-4ff1e980-7a92-11eb-8344-3e45866f57c4.png">

**Comment by lucasferreira** [comment]
Hi @cenaHara 

I'm using iOS 14.4 in my iPhone XR right now and everything works OK.

Could you test some of our test sample projects in your device? https://github.com/lucasferreira/react-native-flash-message/tree/master/examples the expo base one it's more easy to go.

If our sample projects works in your device, than the problem will be in you code.

In external look to your complex structure code I see to many deep levels of nodes, and some modals (flash message will not shown inside native modals).

**Comment by cenaHara** [comment]
hi @lucasferreira 
Yes I will check again, I run on iphone 7 plus, the problem on the simulator still shows normal, and on the ios 13.7 it shows normal, but the real device does not show, I will check the example friend

**Comment by fdelavra** [comment]
I have exactly the same problem with my iPhone X on iOS 14.3
launching showMessage function do nothing.

code: 
<Pressable onPress={() => showMessage({
          message: 'Shared',
          position: 'center'
})} />

don't work neither on emulators
