### ISSUE TITLE
Add testID to typings

### ISSUE THREAD

**Issue by whalemare** [lucasferreira/react-native-flash-message#147]
This library has [testID](https://github.com/lucasferreira/react-native-flash-message/blob/e1fcadcae4e2f36236f63786f6f0fd639be32633/src/FlashMessage.js#L611) property but typings not show it in autocomplete

Please, add this property to library typings.
<img width="357" alt="Снимок экрана 2021-03-08 в 16 46 17" src="https://user-images.githubusercontent.com/9128731/110304146-cf049600-802d-11eb-8c60-6a8d25e95bc9.png">

**Comment by lucasferreira** [comment]
Hi @whalemare 

This was done in the lastest version of our lib.
