### ISSUE TITLE
onPress does not trigger when using <flashmessage/> in modal

### ISSUE THREAD

**Issue by tarikpnr** [lucasferreira/react-native-flash-message#153]
Hello.  I have a modal and I am showing flash message inside of it. I am showing it by using its ref. 

![image](https://user-images.githubusercontent.com/61876765/117167671-22962480-add0-11eb-902a-2bf8d74ba750.png)

The thing is, onPress does not seem to be triggering properly when using in modal by refs.  I do want to hide flash message by onPress function in a modal. So I tried even console.log in onPress  of config, did not get any result back.
Is it known issue that onPress does not work when using by refs in a modal or what am I missing ?  Or at least is there any way to check if flash message is shown in the screen or not ? Maybe that could help as well

And lastly onPress triggers when using normally, without refs and not in any modal. So I thought it might be related with refs ?

![image](https://user-images.githubusercontent.com/61876765/117168836-32623880-add1-11eb-984d-7b7ba646e992.png)

**Comment by tarikpnr** [comment]
No updates yet ?

**Comment by lucasferreira** [comment]
Hi @tarikpnr,

Can you create some Expo Snack (https://snack.expo.io/) with some code demonstrating your problem with Modal?

**Comment by turgay2317** [comment]
Could you solve it? @tarikfp

**Comment by turgay2317** [comment]
OK, I've solved the problem, it was because of using the inner element of flash message.
