### ISSUE TITLE
Notification does not come down as far on iPhone XR

### ISSUE THREAD

**Issue by CRiva** [lucasferreira/react-native-flash-message#16]
I see you have custom heights/widths for iPhone X and ipad:
```
const X_WIDTH = 375; // iPhone X
const X_HEIGHT = 812; // iPhone X
const PAD_WIDTH = 768; // iPad
const PAD_HEIGHT = 1024; // iPad
```
so it may just mean adding iPhone XR to the mix, but the flash message doesn't appear as clean as iPhone X

iPhone XR
<img width="461" alt="iphonexr" src="https://user-images.githubusercontent.com/5423533/48792124-4882e980-eca8-11e8-9a91-dcef1ad44b4a.png">

iPhone X/XS
<img width="425" alt="iphonexs" src="https://user-images.githubusercontent.com/5423533/48792212-84b64a00-eca8-11e8-90fb-c43d66e8389a.png">

**Comment by olivierlesnicki** [comment]
+1

**Comment by rollsroyc3** [comment]
https://github.com/lucasferreira/react-native-flash-message/pull/28

**Comment by lucasferreira** [comment]
Hi @CRiva and @olivierlesnicki 

Thanks to @rollsroyc3 who sent us a great PR!

Now the latest version of `react-native-flash-message` supports all the "notches".
