### ISSUE TITLE
React.children.only expected to receive a single react element child

### ISSUE THREAD

**Issue by saikiranoptisol** [lucasferreira/react-native-flash-message#17]
My App.js render is 

render() {
        return (
            Provider store={StoreConfig}
                RootNavigator/
                FlashMessage position="top" /
            /Provider
        )
    }

if i remove  FlashMessage position="top"  my app is working fine. If i use that step i'm getting the error as 'React.children.only expected to receive a single react element child'

**Comment by lucasferreira** [comment]
Hi @saikiranoptisol 

Your problem it's in <Provider /> not in <FlashMessage />. You have some possibilities to fix this:

1 - Try to use Fragment:

```jsx
import React, { Component, Fragment } from "react"; // don't forget to import the Fragment component from  "react"

....
....
....

export default YourApp extends Component {
  render() {
    return (
      <Provider store={StoreConfig}>
        <Fragment>
          <RootNavigator />
          <FlashMessage position="top" />
        </Fragment>
      </Provider>
    )
  }
}
```

2 - Or just use some View:

```jsx
import React, { Component} from "react";
import { View } from "react-native";

....
....
....

export default YourApp extends Component {
  render() {
    return (
      <Provider store={StoreConfig}>
        <View>
          <RootNavigator />
          <FlashMessage position="top" />
        </View>
      </Provider>
    )
  }
}
```

_PS.: Using `View` you maybe need some style like flex: 1 and etc._

Can you try it?

**Comment by saikiranoptisol** [comment]
@lucasferreira  will check and update. But before that will this flash message work when there is a modal enabled

**Comment by lucasferreira** [comment]
Hi @saikiranoptisol 

react-navigation "Modal" will work.

But if you need to use the RN Modal component (the core one) the FlashMessage will work only if you put a local instance inside the Modal.

**Comment by saikiranoptisol** [comment]
local instance in the sense. can you give an example becuse i'm using RN Modal component

**Comment by lucasferreira** [comment]
Sure @saikiranoptisol!

Here in this issue https://github.com/lucasferreira/react-native-flash-message/issues/1 we have a possible solution.

If you prefer you can go right to this snack: https://snack.expo.io/@lucasferreira/flash-message-modal-demo

The secret it's declare a second instance inside the Modal code, with some ref prop. After that when you are inside the modal, you could call for local messages, with something like this:

`this.refs.YourFlashMessageRef.showMessage(...)`

Got it?

**Comment by saikiranoptisol** [comment]
I'm not sure that one will work if i use modal in seperate js file as a component. Any way will try creating one. thank you @lucasferreira

**Comment by saikiranoptisol** [comment]
@lucasferreira  I have tried you sugesstion to take local ref but I'm using modal as a componnent and calling it in differnt Js files. during this it is showing error as cantRead property showMessage of undefined 

My code in Component
`import FlashMessage, {showMessage} from "react-native-flash-message";
<Modal
                animationType="slide"
                transparent={false}
                isVisible={isVisible}
                style={{margin:0}}
                onModalHide={() => {
                }}
            >
<ScrollView contentContainerStyle={{flexGrow: 1,}}>
                    <View style={{flex: 1, flexDirection: "row"}}>
                    </View>
                    <FlashMessage ref="modalFlash" position="top" />
                </ScrollView>
            </Modal>
`

and i'm using this component in another JS File and call the refrence there as 

- 

`import {showMessage} from 'react-native-flash-message'
setTimeout(() => {
                this.refs.modalFlash.showMessage(`Hello World!`)
            }, 100);
`
showing error as showMessage is not defined. I

**Comment by lucasferreira** [comment]
Hi @saikiranoptisol 

I will close this issue since the main problem "React.children.only" are now solved.

But we can keep chatting about your Modal issue. You're right about this Modal-cross-component thing, and there are a few ways to solve it. I have to find the easy one a ship it with a future new version of FlashMessage.

I don't know what is your React version, but if you use some version >= 16.3 you can solve this problem with `React.createRef()`. You can create some ref in your main Component _(that's instantiate your Modal Component)_ and pass your flashMessageRef down.

I've made a sample at Snack Expo: https://snack.expo.io/B1MJsrSJ4

What do you think?

**Comment by saikiranoptisol** [comment]
This is what I'm looking for. Thank you @lucasferreira  much appreciated
