### ISSUE TITLE
My component keeps getting cutted as i click on it

### ISSUE THREAD

**Issue by Renan-Olovics** [lucasferreira/react-native-flash-message#175]
i'been walking around for hours and i couldnt find any solution for this:

https://user-images.githubusercontent.com/9964502/131900237-cc98a455-10c8-4d16-84a0-d2bf8974fc43.mp4

My app:

```
export default function App() {
  const [fontsLoaded] = useFonts({
    Raleway_100Thin,
    Raleway_300Light,
    Raleway_400Regular,
    Raleway_700Bold,
  })

  if (!fontsLoaded) {
    return <AppLoading />
  } else {
    return (
      <>
        <StatusBar barStyle="light-content" translucent />
        <Provider store={store}>
          <Routes />
        </Provider>
        <FlashMessage position="top" />
      </>
    )
  }
}
```

My Show message:
```            showMessage({
              message: (
                <MessageOnlineOffline
                  title={translate('youAreOnline')}
                  eyeType={<EyeSVG color="white" size={50} />}
                />
              ),
              backgroundColor: '#BE9550',
              statusBarHeight: 50,
              style: styles.FlashMessageCard,
            })
```

My Component:
```
 function MessageOnlineOffline({ title, eyeType }) {
    return (
      <View style={styles.FlashMessageContainer}>
        <Text style={styles.FlashMessageText}>{title}</Text>
        <View style={styles.FlashMessageCircle}>{eyeType}</View>
      </View>
    )
  }
```

My Styles:
``` 
FlashMessageContainer: {
    width: wp('100%'),
    justifyContent: 'space-around',
    flexDirection: 'row',
    alignItems: 'center',
    height: 90,
    backgroundColor: 'red',
  },
  FlashMessageText: {
    maxWidth: 270,
    textAlign: 'center',
    color: 'white',
    fontFamily: ralewayFont.ralewayBold,
  },
  FlashMessageCircle: {
    borderColor: 'white',
    borderWidth: 3,
    borderRadius: 50,
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp('5%'),
  }
```

**Comment by Renan-Olovics** [comment]
as far as i get, theres some problem with the status bar height, on first appearence, it uses the statusBarHeight props, but then if you keep clicking on it, it doubles the value, thats what i think

**Comment by lucasferreira** [comment]
Hi @Renan-Olovics 

I guess that you are passing a **Component** in _message_ inside `showMessage`.

Our component doesn't accept this kind of use inside `showMessage`. As you can see here:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L229

The `message` value that came from `showMessage` it's a string that are shown inside a `Text` component.

If you need to personalize your message component you have to use the MessageComponent prop of `<FlashMessage />`.

So if you need to change icon, you could use `renderFlashMessageIcon ` and if you need to set some custom font or some custom styles for your text, you could use `textStyle` or `titleStyle`. 

And to complete, I guess that `translucent` prop in your StatusBar could affect the _statusBarHeight_ also.
