### ISSUE TITLE
Warning: EventEmitter.removeListener('change', ...): Method has been deprecated.

### ISSUE THREAD

**Issue by imomer** [lucasferreira/react-native-flash-message#176]
I'm using RN 0.65.1 and install react-native-flash-message module on a newly created app. When ever I run the flash message I got this warning:

`WARN  EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by EventEmitter.addListener.
TouchableWithoutFeedback@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flashmsgapp&modulesOnly=false&runModule=true:77383:36
RCTView
View
AnimatedComponent@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flashmsgapp&modulesOnly=false&runModule=true:67484:80
AnimatedComponentWrapper
FlashMessage
RCTView
View
SafeAreaView@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flashmsgapp&modulesOnly=false&runModule=true:80474:41
App
RCTView
View
RCTView
View
AppContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flashmsgapp&modulesOnly=false&runModule=true:75604:36
FlashMsgApp(RootComponent)@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.flashmsgapp&modulesOnly=false&runModule=true:82460:28`

A friend of mine using the same module but his app RN is a bit older (0.64.2)

![Screenshot_1630905558](https://user-images.githubusercontent.com/773535/132164463-9ba21545-8d54-4e4b-a15a-71b399e79b50.png)

**Comment by nericode** [comment]
I have a same issue `EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.`

Environment:

 "react": "17.0.2",
    "react-native": "0.65.1",

**Comment by Sadathossain** [comment]
This [patch](https://gist.github.com/Sadathossain/461c6829c3a47ec1255eaaa318481e18) worked for me.

**Comment by lucasferreira** [comment]
Hi folks,

The last update published in NPM had a fix to this event warning.

Thanks for the reporting ;)
