### ISSUE TITLE
Not working with createSwitchNavigator when using react-navigation

### ISSUE THREAD

**Issue by paschaldev** [lucasferreira/react-native-flash-message#18]
This library works flawlessly with `createStackNavigator` but doesn;t work with `createSwitchNavigator`.

I have a root layout all my components are wrapped with set like this.

This happens with `react-navigation` library

```jsx
render(){

        {
            return this.state.fontLoaded ? 
                (
                    <View style={{flex: 1}}>
                        { this.props.children }
                        <FlashMessage position="top" titleStyle={{ fontFamily: 'maven-pro' }}/>
                    </View>
                ) : null
        }
    }
```

**Comment by lucasferreira** [comment]
Hi @paschaldev 

I never used `createSwitchNavigator` but you tried insert the `FlashMessage` above the Navigator, like this: https://snack.expo.io/Hy7Y01Yc7 ?

**Comment by paschaldev** [comment]
@lucasferreira When I was using `createStackNavigator`, everything worked perfectly but the moment I switched to `createSwitchNavigator` the flash messages render on some screens and doesn't render at all on theres.

I needed to use a switch so separate my `Guest` navigation with my `Auth` navigation stack. Now the flash messages works in screens in the `Auth` but not the one in the `Guest`

**Comment by lucasferreira** [comment]
Hi @paschaldev,

As I said before, you should simply put your `FlashMessage` instance "above" of your SwitchNavigator.

I've made some Snack to you look how this concept works: https://snack.expo.io/SJeRzoM1V

Could you look if it fits in your needy?

**Comment by lucasferreira** [comment]
Hi @paschaldev 

Why you need to use this "RootLayout" component everywhere?

I've modify your sample to work with react-navigation version 3 and with FlashMessage: https://snack.expo.io/ryfpGfXJ4

As you can see in the snack above, I've just instantiate the  `<AppContainer />` as a component and keep the <FlashMessage /> in a context upper higher than Stacks.

**Comment by paschaldev** [comment]
I use a custom fonts in my app so my Root layout is basically used to Load this font, I need to wrap my other screens around it because of the `async` function for loading fonts, so instead of the app reloading fonts / re-flashing, it shouldn't render anything until fonts are loaded.

Here is the content of my `RootLayout`. Any help will be appreciated.

```js
import React from 'react'
import { Font } from 'expo';

import { View, AsyncStorage } from 'react-native'
import FlashMessage from "react-native-flash-message";

import {
    setCustomText, 
    setCustomTextInput
} from 'react-native-global-props'

class RootLayout extends React.Component {

    state = {

		fontLoaded: false,
	};

	async componentDidMount() {

        // await AsyncStorage.removeItem('authData') 

		await Font.loadAsync({
			'maven-pro-black': require('../assets/fonts/MavenPro-Black.ttf'),
			'maven-pro-bold': require('../assets/fonts/MavenPro-Bold.ttf'),
			'maven-pro': require('../assets/fonts/MavenPro-Regular.ttf'),
			'maven-pro-medium': require('../assets/fonts/MavenPro-Medium.ttf'),
		});

        // Set default font 
        const customTextProps = {
            style: {

                fontFamily: 'maven-pro'
            }
        }

        const customTextInputProps = {

            placeholderTextColor: "#333",
            style: {
                fontFamily: 'maven-pro'
            }
        }

        setCustomText(customTextProps)
        setCustomTextInput(customTextInputProps)
        
        this.setState({ fontLoaded: true });

	}

    render(){

        {
            return this.state.fontLoaded ? 
                (
                    <View style={{flex: 1}}>
                        { this.props.children }
                        <FlashMessage position="top" titleStyle={{ fontFamily: 'maven-pro' }}/>
                    </View>
                ) : null
        }
    }
}

export default RootLayout
```

**Comment by paschaldev** [comment]
Running that your snack doesn't work on Android but it works on iOS, can you confirm.... 

![screenshot 2018-12-03 at 11 41 54 pm](https://user-images.githubusercontent.com/13323281/49406182-1a47e400-f755-11e8-8898-2a03bb32fec9.png)

**Comment by lucasferreira** [comment]
Hi @paschaldev I will close this issue since the main "problem" about `createSwitchNavigator` are solved.

For your other trouble I've recommend you to use the FlashMessage option `floating={true}`:

`<FlashMessage position="top" floating={true} />`

This option will modify a little the layout of FlashMessage, but will help eliminating the extra paddingTop inside the message.

Other option it's don't use the "androidStatusBar" thing in app.json. I don't like this "straight fixed bar" of android since the other devices like iPhone (principle iPhone X, XR and XS) it's possible to do it cause "the notch" of device. If you really need to made some black bar in android, you could use the StatusBar module of REACT NATIVE https://facebook.github.io/react-native/docs/statusbar#setbackgroundcolor and not this "androidStatusBar.backgroundColor".

You could try something like that:

```jsx
import { StatusBar } from "react-native";

.....
.....

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <StatusBar backgroundColor="black" barStyle="light-content" />
        <AppContainer />
        <FlashMessage position="top" />
      </View>
    );
  }
}
```

**Comment by paschaldev** [comment]
Thanks very much for your help @lucasferreira I appreciate
