### ISSUE TITLE
React Native Web Error

### ISSUE THREAD

**Issue by hsavit1** [lucasferreira/react-native-flash-message#183]
using RNW 17, RN 63.4, latest 
react-native-flash-message 

./node_modules/react-native-flash-message/src/FlashMessage.js
SyntaxError: /Users/me/my_app/node_modules/react-native-flash-message/src/FlashMessage.js: Support for the experimental syntax 'jsx' isn't currently enabled (154:12):

  152 | export const renderFlashMessageIcon = (icon = "success", style = {}, customProps = {}) => {
  153 |   if (!!DefaultIcons[icon]) {
> 154 |     return <Image style={[styles.flashIcon, style]} source={{ uri: DefaultIcons[icon] }} {...customProps} />;
      |            ^
  155 |   }
  156 | 
  157 |   return null;

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

**Comment by lucasferreira** [comment]
Hi @hsavit1 

As shown in the last part of your `error message` it's just a setup/config problem of your app

```Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.```

Please follow the right instructions to get JSX working in your web app.
