### ISSUE TITLE
Height cut off

### ISSUE THREAD

**Issue by nkenobi** [lucasferreira/react-native-flash-message#184]
Hi,

Appreciate this useful component. Just came across an issue.

The height seems to get cut off to one line if position is 'center'.
Works ok if default position at top.
Happens at least on iPhone11 and iPhone12 (simulator).

Seems related to https://github.com/lucasferreira/react-native-flash-message/issues/126
I've updated to latest 0.2 version and also the dependency helper lib.

Thanks!

**Comment by lucasferreira** [comment]
Hi @nkenobi 

Can you share a image/print with us to show better your issue?

**Comment by prasad-11-cairs** [comment]
![image](https://user-images.githubusercontent.com/90673303/140475514-a2c3f9f2-34c4-4dab-b3eb-47654ea9a034.png)

**Comment by lucasferreira** [comment]
Hi @nkenobi 

That was fixed in the latest version of this package ;)
