### ISSUE TITLE
testing 

### ISSUE THREAD

**Issue by mustafakameldev** [lucasferreira/react-native-flash-message#185]
I'm trying to test by react-native testing library but I got this error 

```  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

   /node_modules/react-native-flash-message/src/index.js:2
    import FlashMessageWrapper, { getFlashMessageStatusBarHeight, styleWithInset } from "./FlashMessageWrapper";
    ^^^^^^
```

**Comment by lucasferreira** [comment]
Hi @mustafakameldev 

I'm not a Jest specialist but it seems to be a config problem, some links that I found:

https://stackoverflow.com/a/51224088
https://stackoverflow.com/a/53670372
https://github.com/vuejs/vue-cli/issues/1584#issuecomment-630430214
https://github.com/vuejs/vue-cli/issues/1584#issuecomment-779155692

**Comment by zhiln** [comment]
@mustafakameldev hey, did you find a way to solve this? I have exactly the same thing:(

**Comment by mustafakameldev** [comment]
Hey@zhiln, I'm tired a lot but nothing works for me

**Comment by zhiln** [comment]
@mustafakameldev I spent some time on it and finally, adding this to the Jest configuration helped me:

```
"transformIgnorePatterns": [
      "node_modules/(?!(jest-)?@react-native|react-native|react-native-flash-message/*)"
    ],
```
Inspired by https://stackoverflow.com/a/55803188

**Comment by mustafakameldev** [comment]
@zhiln I did that and the issue still there

**Comment by mustafakameldev** [comment]
@zhiln 

> @mustafakameldev I spent some time on it and finally, adding this to the Jest configuration helped me:
> 
> ```
> "transformIgnorePatterns": [
>       "node_modules/(?!(jest-)?@react-native|react-native|react-native-flash-message/*)"
>     ],
> ```
> 
> Inspired by https://stackoverflow.com/a/55803188

I did it but I got another issue 
```  ● Test suite failed to run

    .../node_modules/@react-native/polyfills/error-guard.js:14
    type ErrorHandler = (error: mixed, isFatal: boolean) => void;
         ^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/react-native/jest/setup.js:416:6)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.162 s
Ran all test suites matching /savedJobs/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by mustafakameldev** [comment]
> @mustafakameldev I spent some time on it and finally, adding this to the Jest configuration helped me:
> 
> ```
> "transformIgnorePatterns": [
>       "node_modules/(?!(jest-)?@react-native|react-native|react-native-flash-message/*)"
>     ],
> ```
> 
> Inspired by https://stackoverflow.com/a/55803188

Thanks that's helped
