### ISSUE TITLE
autoHide timeout not being cleaned up on unmount

### ISSUE THREAD

**Issue by ecklf** [lucasferreira/react-native-flash-message#186]
This becomes an issue when using `react-native-flash-message` within a modal (https://github.com/lucasferreira/react-native-flash-message/issues/134). 

The user could close the modal before the timeout runs out, which would cause a state update on an unmounted component.

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L471

**Comment by andrefreisf** [comment]
I've encountered the same issue and although this is a work around, I think it's acceptable given you have to use a `FlashMessage` inside the modal anyway. Set `autoHide` to `false` and set your own timeout after `showMessage`. Don't forget to add your own clean up on unmount.

I use a hook to make this task a bit easier:
```
export const useFlashMessage = () => {
    const timer = useRef(undefined);

    useEffect(() => {
        return () => {
            hideMessage();
            clearTimeout(timer.current);
        };
    }, []);

    const displayMsg = (msgOptions: MessageOptions) => {
        clearTimeout(timer.current);
        showMessage(msgOptions);
        timer.current = setTimeout(() => hideMessage(), 2000);
    };

    return { displayMsg };
};
```

**Comment by lucasferreira** [comment]
Hi @ecklf and @andy-fer 

I couldn't simulate this problem here, but to guarantee we insert a clearTimeout at componentWillUnmount function:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L405

I hope that solve your problems.
