### ISSUE TITLE
renderCustomContent placement in message

### ISSUE THREAD

**Issue by ChenCodes** [lucasferreira/react-native-flash-message#187]
Hi there, I was wondering if there is a way to decide where the `renderCustomContent` element can be positioned? Right now it looks like it's always placed underneath the title, but would there be a way for me to indicate that it should be placed on the left of the messages?

This is what I'm looking to achieve:
<img width="372" alt="Screen Shot 2021-12-30 at 4 21 37 PM" src="https://user-images.githubusercontent.com/7213887/147796059-5953eaf1-937f-4585-a80c-3b1fb64c4d1b.png">

I basically have a custom icon that I want to have rendered on the left of the title / text message strings.

Any help would be greatly appreciated!

**Comment by lucasferreira** [comment]
Hi @ChenCodes 

You could use `renderFlashMessageIcon` to achieve that.
