### ISSUE TITLE
cannot access customProps in renderFlashMessageIcon

### ISSUE THREAD

**Issue by ChenCodes** [lucasferreira/react-native-flash-message#188]
Hi there,

I was wondering if there is a way for me to pass props in for `customProps`?

I am trying to build a custom icon that is rendered in the message banner, and since `icon` only takes in a string, I need some other means of passing down data that is needed to render the icon that is shown in the banner. I was hoping to use `customProps` but it looks like I'm unable to pass that down.

Here is my setup:
```
showMessage({ icon: 'avatar', customProps: { avatarUri: 'someString' } });
```

```
const customRenderFlashMessageIcon = (icon = '', style = {}, customProps = {}) => {
    console.log('what is customProps', customProps); // this always shows an empty object
    if (icon === 'avatar') { return <CustomIcon />
    return null;
};
```

Any help would be greatly appreciated!

**Comment by lucasferreira** [comment]
Hi @ChenCodes 

We covered this in the latest version of flash message package, please update your install and run some code like that:

```showMessage({ icon: 'avatar', iconProps: { avatarUri: 'someString' } });```

The real prop now it's called `iconProps` and you will receive that in third argument of `customRenderFlashMessageIcon `.
