### ISSUE TITLE
Allow specifying zIndex

### ISSUE THREAD

**Issue by devth** [lucasferreira/react-native-flash-message#19]
Otherwise it can sometimes be hidden underneath absolute positioned views that have a higher zIndex.

**Comment by lucasferreira** [comment]
Hi @devth 

You could pass some `style` prop:

```jsx
<FlashMessage position="top" style={{ zIndex: 1000 }} />
```

OK?

**Comment by devth** [comment]
Perfect. Thanks @lucasferreira! Might be useful to add to the [props docs](https://github.com/lucasferreira/react-native-flash-message#props).
