### ISSUE TITLE
Outdated Expo SDK Flash Message Playground

### ISSUE THREAD

**Issue by schuler-ph** [lucasferreira/react-native-flash-message#192]
The playground expo app uses SDK 40.0.0, but the current iOS App Store version of Expo Go only supports SDK 41, 42, 43 or 44. Please update the expo version of the demo.

**Comment by lucasferreira** [comment]
Hi @schuler-ph 

Thanks for this warning! It's updated in the latest published version: https://expo.dev/@lucasferreira/FlashMessagePlayground

**Comment by jeoooo** [comment]
@lucasferreira flash message play ground link  is 404 not found

![Image](https://github.com/user-attachments/assets/4c68e2a7-431c-4d1d-b911-05009d902089)
