### ISSUE TITLE
How to make the flash message sticky on scrolling?

### ISSUE THREAD

**Issue by tonydatw** [lucasferreira/react-native-flash-message#196]
I'm trying to figure out how to keep the message box stuck to its absolute position while scrolling a View. Is this even possible or should i show flash messages only inside plain View components?

**Comment by lucasferreira** [comment]
Hi @tonydatw just put in root level, not inside ScrollView. If it was in root level the FlashMessage should be above everything.

**Comment by tonydatw** [comment]
> Hi @tonydatw just put in root level, not inside ScrollView. If it was in root level the FlashMessage should be above everything.

Ops you're right, apologies for the rookie mistake! Ps. Love this package!
