### ISSUE TITLE
transitionConfig

### ISSUE THREAD

**Issue by DenisDov** [lucasferreira/react-native-flash-message#20]
Hi, could you provide a simple example of how to create own transitionConfig? I want to change easing let us say. Thanks.

**Comment by lucasferreira** [comment]
Hi @DenisDov 

In sample app we have this example:
https://github.com/lucasferreira/react-native-flash-message/blob/master/examples/FlashMessagePlayground/screens/CustomTransitionScreen.js

What do you think?

**Comment by DenisDov** [comment]
Oh! It's my inattention. And thanks for this perfect component.
