### ISSUE TITLE
Where to set in DrawerNavigation

### ISSUE THREAD

**Issue by paul29m** [lucasferreira/react-native-flash-message#21]
I want to use this type of message but it does not work properly... 
I know you have to put some were globally but i can't figure it out..
When i show the message is like in the pictures. 
![screenshot_1545928539](https://user-images.githubusercontent.com/18123875/50487278-4ed25700-0a06-11e9-9c43-0122ead0c6b1.png)

This is my App.tsx:

`import * as React from 'react';
import { Dimensions } from 'react-native';
import { DrawerNavigator } from 'react-navigation';

import SideMenuComponent from './side-menu/side-menu.component';
import { stackNavigator } from './stack.navigator';

const App = DrawerNavigator({
    App: {
        screen: stackNavigator
    }
}, {
    contentComponent: SideMenuComponent,

    drawerWidth: Dimensions.get('window').width * 0.8
});

export default App;`

**Comment by lucasferreira** [comment]
Hi @paul29m,

Can you look at this 2 issues?

https://github.com/lucasferreira/react-native-flash-message/issues/13
https://github.com/lucasferreira/react-native-flash-message/issues/18

Perhaps it isn't DrawerNavigator, the solution it's the same, you have to put the _FlashMessage_ "above" your navigators.

**Comment by paul29m** [comment]
I tried to put it in various places but i'm a noob with react and i just did a refactor on that screen so the error has enough space to display :smile:
