### ISSUE TITLE
How to showmessage in <Portal/>

### ISSUE THREAD

**Issue by chukiatt** [lucasferreira/react-native-flash-message#214]
Hi i have a problem about showMessage in Modal that wrapped in <Portal/> and i already have instance in portal like this

   <P.Portal>
      <FlashMessage ref={myRef} position="bottom" floating={true} />

but it still display behide the modal 

please help...

**Comment by lucasferreira** [comment]
Hi @chukiatt 

Modals are a common issue here, look this usual answer: https://github.com/lucasferreira/react-native-flash-message/issues/134

Basically when you work with something that uses another native layer that are "above" the original RN layer we can't surpass this, so you have to put a second local <FlashMessage/> near your modal stuff to resolve this.

**Comment by chukiatt** [comment]
Thank you
