### ISSUE TITLE
Feature suggestion - Add buttons/JSX

### ISSUE THREAD

**Issue by kickbk** [lucasferreira/react-native-flash-message#218]
Thanks for this useful lib.
Quick thought - you already have the `onPress` attribute, which is obviously great. However, one may want more than one action options on one alert, like "Confirm" and "Deny", and I can think of other components one may want to add to the alert. It would be nice to add buttons attribute or the ability to render jsx in addition to `message` and `description`. Perhaps below it.

**Comment by mvolonnino** [comment]
Or a callback button all the way to the right like so many toast options, especially when this is used as a notification in app, can have 'view' rendered all the way to the right, with the title and description center aligned in a row

**Comment by lucasferreira** [comment]
Hi @mvolonnino 

Thanks for this suggestion, in the last version of this lib we add 2 new methods: `renderBeforeContent` and `renderAfterContent`.

`renderBeforeContent` will place a custom render method before everything and `renderAfterContent` will place a custom render method after everything, and this `after place` it is what you need to put some custom buttons and etc.
