### ISSUE TITLE
Please, add more example.

### ISSUE THREAD

**Issue by Trapintrovert** [lucasferreira/react-native-flash-message#220]
Thank you for creating this awesome package. You're a lifesaver.

I'm having issues creating a custom icon using renderFlashMessageIcon method. I can't just wrap my head around how it works.
It would be awesome if there is enough examples of how to use this package.

**Comment by Trapintrovert** [comment]
Found a solution.

showMessage({
        message: 'You’re back online!',
        type: 'success',
        icon: 'success',
        renderFlashMessageIcon(icon = 'success', style = {}, iconProps = {}) {
          if (icon) {
            return (
               // Your icon here
              <WifiOnline
                {...iconProps}
                style={{ marginTop: -3, marginRight: 10 }}
              />
            );
          }
          return null;
        },
        style: { paddingTop: 40 },
        textStyle: { fontFamily: 'Mabry-Regular', fontSize: 16 },
      });

**Comment by lucasferreira** [comment]
Hi @Trapintrovert 

The method `renderFlashMessageIcon` it's really difficult to use and to understand, sorry about this.

To facilitate this kind of custom icon interaction, in the last version of this lib we covered a more simple way to show a custom icon, something like that:

```javascript
showMessage({
  message: 'You’re back online!',
  type: 'success',
  icon: (iconProps) => <WifiOnline {...iconProps} style={{ marginTop: -3, marginRight: 10 }} />,
  style: { paddingTop: 40 },
  textStyle: { fontFamily: 'Mabry-Regular', fontSize: 16 },
});
```

Could you update your install and give a try?

**Comment by fukemy** [comment]
i can not modify icon borderradius, can someone help?

```
showMessage({
                                message: roomResult.RoomName,
                                description: language.NewMessage,                      
                                type: "success",
                                statusBarHeight: insets.top,
                                iconProps: { borderRadius: 20 },
                                icon: props => <FastImage source={{ uri: avatarUrl }} style={{
                                    width: 40,
                                    height: 40,
                                    borderRadius: 20
                                }}{...props}/>
                            })
```
