### ISSUE TITLE
Does not render only on IOS

### ISSUE THREAD

**Issue by joaooliveeira** [lucasferreira/react-native-flash-message#224]
**IOS iPhone 14 Pro Max Simulator:** Renders on the first screen, it is necessary to go back in the screen stack.

![Simulator Screen Recording - iPhone 14 Pro Max - 2022-10-01 at 13 19 38](https://user-images.githubusercontent.com/32743016/193418643-2faeb638-7bc2-4de6-9aad-2d463d30ce33.gif)

---

**Android Emulator works fine**

![untitled](https://user-images.githubusercontent.com/32743016/193418575-c89cc8ad-3f48-4b56-94c0-24a96abab096.gif)

I'm using react native navigation versions:
react-navigation/native": "^6.0.13"
react-navigation/native-stack": "^6.9.0"

![Screen Shot 2022-10-01 at 12 37 47](https://user-images.githubusercontent.com/32743016/193417017-d3669fa2-7ac9-49d5-9636-03be9b5a22cd.png)

I already tried the isssues: #13 #11

**Comment by ahofmeister** [comment]
@joaooliveeira Can you please write, what exactly the issue was? I have I think kind of the same problem

**Comment by johnny-washswat** [comment]
Hi, I have a question, 
How did you fix the dynamic island issue.? in my case Flashmesage is coming under the dynamic island

**Comment by joaooliveeira** [comment]
@johnny-washswat 

I don't recommend my solution. I'm currently checking the device model, if it's an iPhone 14 Pro/Pro Plus I add 25 in the paddingTop of the Header component.

If you discovery a solid solution. Please let me know.
