### ISSUE TITLE
Not support iPhone 14

### ISSUE THREAD

**Issue by ryskin** [lucasferreira/react-native-flash-message#225]
There are virtual "notch"

<img width="322" alt="image" src="https://user-images.githubusercontent.com/3756722/194801758-c4ec47cb-f2f0-4996-8ec9-af2e1e79e1aa.png">

**Comment by samuelbeaulieu** [comment]
I think [this PR](https://github.com/ptelad/react-native-iphone-x-helper/pull/44) (or [this one](https://github.com/ptelad/react-native-iphone-x-helper/pull/45)) needs to be merged before the fix can be applied in this package.

**Comment by lucasferreira** [comment]
Hi @samuelbeaulieu you're right on that. We rely on this external lib to calculate status bar height...

If you guys could ask there also to adapt this, we will be safe here too.

**Comment by swey** [comment]
The approach to manually adjust the padding based on `isIPhoneX` is not flexible anyway.

The better approach is using `useSafeAreaInsets`/`SafeAreaInsetsContext.Consumer` to determine the needed extra padding.

**Comment by hbiede** [comment]
I agree that converting to `react-native-safe-area-context` seems like the best move here. The developer of `react-native-iphone-x-helper` themselves even says to make the move because that package is dead.

**Comment by lucasferreira** [comment]
Hi guys @hbiede @swey @samuelbeaulieu and @ryskin,

For now we had changed to a fork of original `react-native-iphone-x-helper` called `react-native-iphone-screen-helper` that has the same API and nothing will changed for usa internally.

As I could look into `react-native-iphone-screen-helper` code their supports iPhone 14 so by now this problem are solved (I guess).

In a near future we will look into changed everything to use `react-native-safe-area-context` because it's seems to be more robust for this measures of notch devices.

Could you help us to test this currently new version?

**Comment by hbiede** [comment]
> Hi guys @hbiede @swey @samuelbeaulieu and @ryskin,
> 
> For now we had changed to a fork of original `react-native-iphone-x-helper` called `react-native-iphone-screen-helper` that has the same API and nothing will changed for usa internally.
> 
> As I could look into `react-native-iphone-screen-helper` code their supports iPhone 14 so by now this problem are solved (I guess).
> 
> In a near future we will look into changed everything to use `react-native-safe-area-context` because it's seems to be more robust for this measures of notch devices.
> 
> Could you help us to test this currently new version?

We switched to passing a `statusBarHeight` prop equal to `useSafeAreaInsets().top` with `showMessage` and that works as expected

**Comment by dkjeune** [comment]
Hi,
The version 4.0.0 seems to solve the problem.
How to install it ?
on NPM, the last version is  0.3.1

**Comment by lucasferreira** [comment]
Hi @dkjeune that's was my bad, I really forgot to publish on npm registry.

Now it's seems to be OK, could try to update again?

**Comment by dkjeune** [comment]
> Hi @dkjeune that's was my bad, I really forgot to publish on npm registry.
> 
> Now it's seems to be OK, could try to update again?

yes it work fine, thanks

**Comment by johnny-washswat** [comment]
I solved this issue by adding 
`import {getStatusBarHeight} from 'react-native-iphone-x-helper';
and also FlashMessage support statusBarHeight

Code:
        <FlashMessage
                position={'top'}
                statusBarHeight={statusHeight + 20}
              />
`

**Comment by samuelbeaulieu** [comment]
@johnny-washswat you shouldn't add a static value to adjust the status bar height, it will not work properly on other devices. You should use the latest version of this library instead which is already fixed for the iPhone 14 pro.
