### ISSUE TITLE
Does not run on a CASIO Handheld running Android 8

### ISSUE THREAD

**Issue by CoderDSS** [lucasferreira/react-native-flash-message#226]
In the emulator it works perfectly, in a CASIO DTX-400 Handheld with Android 8, I can't get it to work.
I am using ReactNative CLI v0.72.3

**Comment by lucasferreira** [comment]
Hi @CoderDSS 

How could we test this besides have one CASIO DTX-400 in hands?

**Comment by CoderDSS** [comment]
Sorry, it was my mistake... I still haven't found it, but I did several tests and this one comes from another part of the code

**Comment by lucasferreira** [comment]
So we can close this issue @CoderDSS ?

**Comment by CoderDSS** [comment]
yes, please
