### ISSUE TITLE
Show Toast Message always appears behind the modal in iOS when it is open using react-navigation 6.x 

### ISSUE THREAD

**Issue by BajajSaajan** [lucasferreira/react-native-flash-message#227]
This is the flow of the application. 
 <Provider
   <App /
   <FlashMessage
  </Provider
When modal is opened and if i call showMessage then toast always show behind the modal. any suggestion or help will be appreciated.

**Comment by lucasferreira** [comment]
Hi @BajajSaajan,

Native modals works on other UI thread so we can't reach there. You could use a local instance inside modal, there are other issues about that, that can help ui:

https://github.com/lucasferreira/react-native-flash-message/issues/134
https://github.com/lucasferreira/react-native-flash-message/issues/167

**Comment by Irfanwani** [comment]
this issue is still there. Though i found a workaround for the Card element (from react native paper) but for modal, nothing works. I even tried to put the component inside the same modal but then the message doesn't even show

**Comment by lucasferreira** [comment]
Hi @Irfanwani inside some Modal with local FlashMessage instance you have to call by ref, like referenced in other issues.

`flashMessageRef.showMessage(....)`

**Comment by Irfanwani** [comment]
@lucasferreira Thanks for the reply. I will try this

**Comment by sheggietyn** [comment]
sad new update and it still doesn't show on modal

**Comment by rkocur** [comment]
+1

**Comment by lucasferreira** [comment]
Hi @sheggietyn @rkocur and @sheggietyn,

Our solution works entirely on JS Thread (not on native layer) so native modals works on other native UI thread so we can't reach there with JS code. But you guys could always run a second instance of FlashMessage inside modal code.

**Comment by sheggietyn** [comment]
i have switched to using this .. you can use it as a case study though 

react-native-toast-message

**Comment by lucasferreira** [comment]
Hi @sheggietyn 

The auto-ref solution of https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md is very clever, but they suffer from same problem that us: you need to create a second instance inside the Modal since they opper in other UI layer.

**Comment by rkocur** [comment]
> Hi @sheggietyn @rkocur and @sheggietyn,
> 
> Our solution works entirely on JS Thread (not on native layer) so native modals works on other native UI thread so we can't reach there with JS code. But you guys could always run a second instance of FlashMessage inside modal code.

yes, i agree. I added FlashMessage inside the modal and it worked. thanks.

**Comment by Yaya12085** [comment]
```
import { FullWindowOverlay } from 'react-native-screens';
import FlashMessage from "react-native-flash-message";

export default function App() {
  return (
    <View style={{ flex: 1 }}>
      <Content />

     <FullWindowOverlay>
          <FlashMessage />
        </FullWindowOverlay>
    </View>
  );
}
```

**Comment by psyzz** [comment]
@Yaya12085 your solution works, but we lost the capacity to click on the banner

**Comment by Yaya12085** [comment]
@psyzz You're right, you should use @lucasferreira 's method.

Here's an example using the method:



`import React, { useCallback, useEffect, useRef } from "react";
import { Text, View } from "react-native";
import RNModal from "react-native-modal";

import { colors, fonts, sizes, spacings } from "@/lib/constants";
import { ScrollView } from "react-native";
import FlashMessage, { FlashMessageManager } from "react-native-flash-message";
import { Button } from "./button";

interface ModalProps {
  visible: boolean;
  onClose: () => void;
  children?: React.ReactNode;
  title: string;
  description?: string;
  onConfirm?: () => void;
  variant?: string;
  confirmLoading?: boolean;
  singleButton?: boolean;
  confirmText?: string;
  cancelText?: string;
}
const Modal = ({
  visible,
  onClose,
  children,
  title,
  description,
  onConfirm,
  variant,
  confirmLoading,
  singleButton = false,
  confirmText = "Confirmer",
  cancelText = "Annuler",
}: ModalProps) => {
  const flashRef = useRef<FlashMessage>(null);
  const captureFlashMessageRef: React.LegacyRef<FlashMessage> = useCallback(
    (ref) => {
      if (ref !== null) {
        FlashMessageManager.hold(ref);
        flashRef.current = ref;
      }
    },
    []
  );

  function unholdFlashMessage() {
    if (!!flashRef.current) {
      FlashMessageManager.unhold();
    }
  }

  function closeModal() {
    unholdFlashMessage();
    onClose();
  }

  useEffect(() => {
    return () => unholdFlashMessage();
  }, []);

  return (
    <RNModal
      isVisible={visible}
      animationIn={"zoomIn"}
      animationOut={"zoomOut"}
      avoidKeyboard={true}
      style={{
        margin: sizes.base,
      }}
      hasBackdrop
      backdropColor={colors.primary}
      backdropOpacity={0.5}
      useNativeDriver
      useNativeDriverForBackdrop
      hideModalContentWhileAnimating
      propagateSwipe
    >
      <View
        style={{
          backgroundColor: colors.white,
          borderRadius: sizes.radius,
          paddingHorizontal: spacings.medium,
          paddingVertical: spacings.large,
          alignItems: "center",
          gap: 10,
          maxHeight: "90%",
        }}
      >
        <View
          style={{
            alignItems: "flex-start",
            width: "100%",
          }}
        >
          <Text style={{ marginBottom: 5, ...fonts.h2 }}>{title}</Text>
          {description && (
            <Text style={{ ...fonts.body, color: colors.gray[600] }}>
              {description}
            </Text>
          )}
        </View>
        <ScrollView
          style={{
            width: "100%",
          }}
          contentContainerStyle={{ flexGrow: 1 }}
          showsVerticalScrollIndicator={false}
        >
          <View
            style={{
              width: "100%",
              alignItems: "center",
            }}
          >
            {children}
          </View>
        </ScrollView>

        <View style={{ flexDirection: "row", gap: 10, alignSelf: "flex-end" }}>
          <Button title={cancelText} variant="ghost" onPress={closeModal} />
          {!singleButton && (
            <Button
              title={confirmText}
              variant={variant as any}
              onPress={onConfirm}
              isLoading={confirmLoading}
            />
          )}
        </View>
      </View>
      <FlashMessage ref={captureFlashMessageRef} position="top" />
    </RNModal>
  );
};

export default Modal;`

**Comment by csalihburak** [comment]
> ```
> import { FullWindowOverlay } from 'react-native-screens';
> import FlashMessage from "react-native-flash-message";
> 
> export default function App() {
>   return (
>     <View style={{ flex: 1 }}>
>       <Content />
> 
>      <FullWindowOverlay>
>           <FlashMessage />
>         </FullWindowOverlay>
>     </View>
>   );
> }
> ```

Thank you it worked in IOS, but this only works for IOS. android gives the warning "Using FullWindowOverlay is only valid on iOS devices. " any advice?
