### ISSUE TITLE
Invalid prop `icon` supplied to `FlashMessage`, expected one of type [string, object].

### ISSUE THREAD

**Issue by ObjectJosh** [lucasferreira/react-native-flash-message#236]
<img width="499" alt="Screen Shot 2023-01-10 at 11 56 48 AM" src="https://user-images.githubusercontent.com/42549561/211649683-83fb0a15-6b9b-4dc6-aa35-b51726973f83.png">

Error with the type of the icon prop for FlashMessage. Comes up every time the app is loaded. Is my usage incorrect, or should it not be raising an error?

Usage in code:
<img width="420" alt="Screen Shot 2023-01-10 at 11 57 44 AM" src="https://user-images.githubusercontent.com/42549561/211649867-40b8a513-415f-4cf4-b0c9-1c142fa844c0.png">

**Comment by lucasferreira** [comment]
Hi @ObjectJosh 

Your usage is wrong, `icon` are passed in `showMessage` function call, like shown in README:

https://github.com/lucasferreira/react-native-flash-message#message-with-custom-icon

And in this examples:

https://github.com/lucasferreira/react-native-flash-message/blob/master/examples/FlashMessagePlayground/screens/MainScreen.js#L30
