### ISSUE TITLE
Android cutoff

### ISSUE THREAD

**Issue by shawarmaz** [lucasferreira/react-native-flash-message#237]
I've tested on 4 different Android device/emulators and I keep getting the same result: the component gets cut off.

Works fine on iOS.

Any clue what could be going on here? 

![Screenshot 2023-01-20 at 3 54 33 AM](https://user-images.githubusercontent.com/81338316/213608127-09cd7e14-f878-47ae-8e80-5b6f1169bd29.png)

**Comment by lucasferreira** [comment]
Hi @shawarmaz maybe you need to work on your StatusBar configurations:

https://reactnative.dev/docs/statusbar

Maybe try some different Android only options, like `translucent` or `backgroundColor`:
https://reactnative.dev/docs/statusbar#translucent-android
https://reactnative.dev/docs/statusbar#backgroundcolor-android

**Comment by shawarmaz** [comment]
@lucasferreira thx for the reply

wouldn't you say this has less to do with color than margin/padding?

**Comment by lucasferreira** [comment]
@shawarmaz if you are not using react-navigation sometimes android acts weird em status bar weight, and show statusbar above the app.

Here a sample that you could test even in browser (just choose android emulator em the right pane):
https://snack.expo.dev/@lucasferreira/flash-message-custom-icon-demo

Other option you could gave more paddingTop in FlashMessage working with `statusBarHeight` prop of FlashMessage main componente, or `style`.

**Comment by shawarmaz** [comment]
@lucasferreira i actually am using react-navigation, weird. I've tried positioning it as the last child of every component

**Comment by shawarmaz** [comment]
got it to work. It was a bug on my end. Thx for the help and for the lib 🤝

**Comment by mateattilabarna** [comment]
@ice-cap0 

Hey, what was your solution on android?
