### ISSUE TITLE
Padding issue when using icon

### ISSUE THREAD

**Issue by lukaspechar** [lucasferreira/react-native-flash-message#24]
When displaying a long message and using an `icon` and `floating` property the container is lacking right padding. This is not an issue when the icon is hidden. Other than that I love this plugin!

**Comment by gpsugy** [comment]
Great plugin for sure, but I am also experiencing this issue. `paddingRight` on the `style` property does nothing when there is an icon.

**Comment by lucasferreira** [comment]
Hi @pechar and @gpsugy 

I will look forward in this issue, but by now, you could use the `textStyle` ou `titleStyle` props/params to adjust your flash message texts.

Have you try that?

**Comment by gpsugy** [comment]
Thanks for responding so quickly, @lucasferreira . Unfortunately, adding either (or both) `textStyle` and `titleStyle` with `{ paddingRight: [any number]` to the message component produces the same result as the screenshot above.

**Comment by timiles** [comment]
In case it helps anyone, the following code is working for me:

```
export default class App extends React.Component {
  render() {
    const myFlashMessageComponent: React.SFC<MessageComponentProps> = (props) =>
      <DefaultFlash {...props} titleStyle={{ paddingRight: 10 }} textStyle={{ paddingRight: 10 }} />;

    return (
      <View style={{ flex: 1 }}>
        {/* Views etc */}
        <FlashMessage position="top" MessageComponent={myFlashMessageComponent} />
      </View>
    );
  }
}
```
