### ISSUE TITLE
MessageOptions and MessageComponentProps interfaces are incorrect

### ISSUE THREAD

**Issue by dmkav** [lucasferreira/react-native-flash-message#240]
index.d.ts has MessageOptions and MessageComponentProps interfaces. Both of them have prop `renderAfterMessage`. However, the correct prop is `renderAfterContent`. 
Could you fix it?

**Comment by dmkav** [comment]
I've created PR

**Comment by lucasferreira** [comment]
Thanks @dmkav ;)
