### ISSUE TITLE
Updating icon props to allow JSX.Element callback

### ISSUE THREAD

**Issue by soupjake** [lucasferreira/react-native-flash-message#243]
I was wondering if it would be possible to update the icon prop type within MessageOptions interface to allow a simple JSX.Element callback? This would make is easier to allow any JSX.Element to be used such as MaterialIcon and so make the prop more flexible.

For example, update:

`icon?: React.ReactElement | Icon;`

to

`  icon?: React.ReactElement | Icon | (() => JSX.Element);`

This will then let you do:

```
icon: () => (
    <MaterialIcon name="warning" color="#ff0000" size={24} />
),
```

The current type of just React.ReactElement doesn't work in this instance:

`Type '() => JSX.Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>> | Icon | undefined'.`

Thanks!

**Comment by lucasferreira** [comment]
Hi @soupjake 

I'm not a TS expert, could you send some PR with this enhance?

**Comment by mssoliveira** [comment]
Hi,

i have this same problem.

**Comment by soupjake** [comment]
> Hi,
> 
> I'm having the same problem, I'll try to solve it directly at the library to see if it solves it and I'll get in touch.

Here's the PR I opened if you want to see the change: https://github.com/lucasferreira/react-native-flash-message/pull/244

**Comment by mssoliveira** [comment]
Hi @soupjake 

in the project that I'm implementing, it still has the problem, even changing it.

**Comment by lucasferreira** [comment]
Hi @soupjake and @mssoliveira,

I've accepted the PR and publish a new version of this lib.
