### ISSUE TITLE
Export interfaces/types in typescript definitions

### ISSUE THREAD

**Issue by budziam** [lucasferreira/react-native-flash-message#25]
Hi,
I'm writing a wrapper around this library (for my project usage). It would be really useful if more definitions were exported like: `MessageOptions`, `MessageType` etc.

I could create a PR with above changes, but first I would like to know what you think about it.

**Comment by lucasferreira** [comment]
That would be great @budziam 

I'm not a TS guy at all, so every help in this aspect will be awesome!

**Comment by themakshter** [comment]
This has been completed in #57 no?
