### ISSUE TITLE
Không thể xoá paddingTop

### ISSUE THREAD

**Issue by 0949328231** [lucasferreira/react-native-flash-message#250]
chào bạn, tôi thấy thư viện bạn làm rất bổ ích, tuy nhiên tôi muốn sửa lại một chút giao diện thông báo (muốn như ảnh) nhưng lại không thể xoá được paddingTop, bạn có thể giúp đỡ tôi được không? cảm ơn bạn nhiều lắm
![IMG_0855](https://user-images.githubusercontent.com/94269034/233777534-17734196-6abf-40fd-bacd-6e147bf3bac1.PNG)
![Ảnh màn hình 2023-04-22 lúc 17 10 10](https://user-images.githubusercontent.com/94269034/233777753-60b7ff49-db57-4426-a8d7-50011a60fddf.png)

**Comment by pnthach95** [comment]
Sửa lại tiếng Anh đi, nói tiếng Việt sao người ta hiểu.

Chỗ này sửa `statusBarHeight` là được
