### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by soheilshiri** [lucasferreira/react-native-flash-message#26]
How can I add styles to this flash message?
I want to change font size and ...

**Comment by lucasferreira** [comment]
Hi @soheilshiri 

Sorry for the delayed answer but we have to props for that: `titleStyle` and `textStyle`.
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L526

You could use in FlashMessage instance:

`<FlashMessage textStyle={{ fontSize: 18 }} />`

or when you call `showMessage`:

`showMessage({ message: 'Hello', textStyle: { fontSize: 18 } });`

Ok?

**Comment by emreozdincer** [comment]
Hi @lucasferreira. I don't want to open an issue for this but the screen freezes when a message is shown, i.e the app doesn't respond to any other touch/swipe/click events while there is a message. Is this intended, and how can I change this behavior?

**Comment by lucasferreira** [comment]
Hi @emreozdincer 

This isn't the expected behavior, as you could see in this snack it's possible to hit the other buttons when the flash message it's shown:

https://snack.expo.io/S130Ws9IN

I don't know if you face some kind of bug or you didn't implement the `<FlashMessage />` instance in correct place.

If you need more help about this, you are free to open some new issue, will be more easy to help you there.

**Comment by moyolvera** [comment]
Hi @lucasferreira 

Firts of all i really like this library, thanks a lot for this. And second, I'm having troubles with typescript validations and showMessage method. There's a reason to not have style property on MessageOptions interface? I need to change the borders and add some shadows to component.

This works but i'm receiving an ts error

showMessage({
   ...messageContent,
   style: styles.someStyles,
});

**Comment by Great-hijack** [comment]
> Hi @lucasferreira. I don't want to open an issue for this but the screen freezes when a message is shown, i.e the app doesn't respond to any other touch/swipe/click events while there is a message. Is this intended, and how can I change this behavior?

Hi @emreozdincer Same issue for me. My iOS app doesn't respond to any user interaction after the message is shown.
It is not all the time but sometimes my app looks like it freezes.

@lucasferreira Any thought?

**Comment by lucasferreira** [comment]
Hi @Great-hijack 

This isn't a normal behavior not even expected for me.

Here a video of the sample project running on my iPhone XR with iOS 14: 
<video src="https://www.dropbox.com/s/w476k5gzmtsssey/demo_flash_message.mp4?dl=1" style="max-width: 420px" controls></video>
https://www.dropbox.com/s/w476k5gzmtsssey/demo_flash_message.mp4?dl=0

As you can see, I can keep change the screens and clicking in a lot of buttons even with the messages still "alives" in the top of screen.
