### ISSUE TITLE
How to use built-in icon?

### ISSUE THREAD

**Issue by isaaclem** [lucasferreira/react-native-flash-message#31]
I've tried with below but the Icon doesnt render

```js
showMessage({
  icon: { icon: 'danger' },
  message: 'Verification failed',
  type: 'danger'
});
```

**Comment by lucasferreira** [comment]
Hi @isaaclem 

In theory as we can see in oficial sample app:

https://github.com/lucasferreira/react-native-flash-message/blob/master/examples/FlashMessagePlayground/screens/MainScreen.js#L18

You can use in this way:

```js
showMessage({
  icon: { icon: "auto", position: "left" },
  message: 'Verification failed',
  type: 'danger'
});
```

When you pass "icon: auto" the flash message will automatically pick an icon that match with the "type" of message.

Got it?
