### ISSUE TITLE
Flash Message Show Only First Time After Install

### ISSUE THREAD

**Issue by enricharcane** [lucasferreira/react-native-flash-message#33]
I installed react native flash message into my project. Then I'm facing to an issue which flash message only show for the first time after install it. In second time i executed react-native run-android command and I didn't get flash message.

I added <FlashMessage position="top" floating={true} /> this as list component and use follow method to show message. Please help me solve this.

showMessage({
          message: "Authentication Failed",
          description: "Your token has been expired. Please log again.",
          type: "warning",
        });

**Comment by lucasferreira** [comment]
Hi @enricharcane,

Your `showMessage` call doesn't help to find your problem.

`react-native-flash-message` it's a pure JS module, without Android or iOS native code, it didn't need you do anything besides `npm install --save react-native-flash-message` and start using it.

If your `showMessage` call are in right place everything should be OK. Or you are not using it (install and importing) in the right way or you could face some android cache in JS compiled code.

When you say "I didn't get flash message" are you facing some error to show us?
