### ISSUE TITLE
duration not working in some android Devices

### ISSUE THREAD

**Issue by saikiranoptisol** [lucasferreira/react-native-flash-message#35]
i'm testing this in Vivo and Samsung device with oreo versions. Here if i set duration to 3000 it's not working. As per the document the default duration is 1850. I guess even this duration is not working. the flash message comes and in no time it goes off. in ios if i check it works fine. Any Suggestions regarding this issue

**Comment by lucasferreira** [comment]
Hi @saikiranoptisol 

We deal with a simple `setTimeout` to hide the message:
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L427

Do you know if in his your device are any problem in using `setTimeout`?

**Comment by saikiranoptisol** [comment]
@lucasferreira  thanks for the quick reply. After some research on set timeout i came to know the main problem. 
                Actually the component is working fine. The issue is with the time difference between my machine and the device. There is 1 min difference in time between my mac machine and device. i just changed the time and it works perfectly.

**Comment by lucasferreira** [comment]
Good to know that @saikiranoptisol ;)
