### ISSUE TITLE
FlashMessage with react-native-router-flux

### ISSUE THREAD

**Issue by Senocico** [lucasferreira/react-native-flash-message#37]
I'm using **react-native-flash-message** with **react-native-router-flux**
I have the following code:

```
const App = () => (
    <Provider store={store}>
        <Router>
            <Stack>
                <Scene key="splashScreen" component={SplashScreen} initial/>
                <Scene key="welcomeScreen" component={WelcomeScreen}/>
                <Scene key="loginScreen" component={LoginScreen}/>
            </Stack>
        </Router>
    </Provider>
)

AppRegistry.registerComponent(appName, () => App)
```

I run 
**Actions.welcomeScreen()** and after **Actions.loginScreen()**

**Both components (screens) have the last rendered component:**
`<FlashMessage floating={true} icon={'auto'}/>`

Even if I am on the **loginScreen** and I run **showMessage()**, the message is shown on the  **welcomeScreen**; 

If the navigation has pushed 3 components and all of them have <`Flash Message/>`, I want for the message to be shown only on the last pushed component, not on the first that is the case of this scenario.

**What should I do in this case?**

**Comment by lucasferreira** [comment]
Hi @Senocico,

I guess that you have to put the `<FlashMessage />` above the router. You could try something like that...

```jsx
const App = () => (
    <Provider store={store}>
        <React.Fragment>
          <Router>
              <Stack>
                  <Scene key="splashScreen" component={SplashScreen} initial/>
                  <Scene key="welcomeScreen" component={WelcomeScreen}/>
                  <Scene key="loginScreen" component={LoginScreen}/>
              </Stack>
          </Router>
          <FlashMessage floating={true} icon="auto" />
        </React.Fragment>
    </Provider>
)

AppRegistry.registerComponent(appName, () => App)
```

Doing this you didn't need to load the FlashMessage inside your scenes/screens.

This is the same solution for react-navigation, so I guess that will work for router-flux too.

**Comment by lucasferreira** [comment]
Hi @Senocico when you test my suggestion, could you tell me if it works?

**Comment by Senocico** [comment]
Works perfectly.
Thank you for suggestion.
