### ISSUE TITLE
How to show the flash message in any screen with by calling showMessage() Method at particular screen

### ISSUE THREAD

**Issue by mahesh963** [lucasferreira/react-native-flash-message#41]
Hi, thanks for the awesome module. My requirement is, In my app i'm using chat functionality i need to show the notification type messages by calling **showMessage()** once in single screen and need to get notification message in anywhere in the Application. Can you please suggest me how to fix it.

**Comment by lucasferreira** [comment]
Hi @mahesh963 

I don't know if I get your problem, cause what are you are ask me it's **really what this module do**.

If you see this samples:

https://github.com/lucasferreira/react-native-flash-message/tree/master/examples/FlashMessagePlayground

https://snack.expo.io/Hy7Y01Yc7

You could see that really works in the way that you need, you just need to insert the <FlashMessage /> on top of your component root and than you can cal `showMessage` in any screen.

**Comment by mahesh963** [comment]
Hi @lucasferreira  thanks for the quick response. Calling the method **showMessage()**  in any screen shows the flash-message in that particular screen. But, here my question is i need to call the **showMessage()** at only one screen whenever the message changes in that screen i need to get flash message if i was not in that screen. Is that possible?

**Comment by affanhashone** [comment]
@mahesh963  please create a seperate a file and export that method with your message as a param
