### ISSUE TITLE
How do we access a non-global flash-message?

### ISSUE THREAD

**Issue by aktasfatih** [lucasferreira/react-native-flash-message#42]
I have figured out how to access the global FlashMessage component. 

However, I want to have a second FlashMessage component positioned in another View in another screen. 

I realize that the non-global FlashMessage is supposed to be like below with a ref. But, how do I access the non-global FlashMessage to show a message?
```
<FlashMessage ref="myNonGlobalFlashMessage" /> 
```

Or am I doing something completely wrong? 
What I am trying to accomplish is, I want to have this FlashMessage in a scrollview under the Header. So, I wrapped up my ScrollView with a View, and put the FlashMessage under the ScrollView. Pretty much like below,

```
<View>
  <ScrollView> ...</ScrollView>
  <FlashMessage.. />
</View>
```
But, I can't get it to show a message.

**Comment by spyr0s** [comment]
Have you tried 
this.myNonGlobalFlashMessage.showMessage({...options})

**Comment by lucasferreira** [comment]
Hi @aktasfatih and @spyr0s 

If you work with "string" refs, you go like this:

`this.refs.myNonGlobalFlashMessage.showMessage(....);`

Like this sample working with native Modals: https://snack.expo.io/@lucasferreira/flash-message-modal-demo

**Comment by spyr0s** [comment]
In my case is
```
flashMessage: React.RefObject<any> = React.createRef();

this.flashMessage.current.showMessage({})
```

**Comment by lucasferreira** [comment]
Yep @spyr0s in case of ref object your are correct...

**Comment by aktasfatih** [comment]
@lucasferreira 
I definitely didn't know about refs. The code below worked like a charm. Thank you!
```this.refs.myNonGlobalFlashMessage.showMessage(....);```

<img width="300" alt="portfolio_view" src="https://user-images.githubusercontent.com/12985956/57897476-1cd55c00-7812-11e9-93f4-d33dad64a6ae.jpg">

**Comment by dentep** [comment]
Found this issue so far away, thank you for your help!
