### ISSUE TITLE
Is it possible to define different renderCustomContent per message?

### ISSUE THREAD

**Issue by gabrielgc** [lucasferreira/react-native-flash-message#44]
I'm using the `<FlashMessage>` globaly on my App and I have to define a different View depending on the message type I have.
Is it possible to define it at the `showMessage() `level instead of at the `<FlashMessage>` level ?

**Comment by lucasferreira** [comment]
Hi @gabrielgc nopz, it is not possible.

But you could personalize a lot of stuff directly in `showMessage` call, like `style`, `textStyle` and `titleStyle`.

**Comment by gabrielgc** [comment]
Yes, they're nice style options, but in my scenario is a bit more complicated than a stylish message.
I'll fork the project and see if I can get something more message based.

Thanks
