### ISSUE TITLE
fontFamily is not working for android title style

### ISSUE THREAD

**Issue by mahdidavoodi7** [lucasferreira/react-native-flash-message#45]
Hi , fontFamily is not working for titleStyle on android

```javascript
//render

<FlashMessage animated={true} textStyle={styles.messageTextStyle} titleStyle={styles.messageTitleStyle} ref="fmLocalInstance" position='top'/>

//style

messageTitleStyle:{
    textAlign:"right",
    color: 'white',
    fontSize:16,
    ...Platform.select({
      ios: {
        fontFamily: "IRANSansMobileNoEn",
        fontWeight: '300',
      },
      android: {
        fontFamily: "IRANSansMobile(NoEn)_Light",
      },
  }),
},
```

Please solve this issue

**Comment by lucasferreira** [comment]
Hi @mahdidavoodi7 

As we could se here the `textStyle` it's right passed down to the text component:
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L224

So I guess that is something in your setup.

I can use this "custom font" in other places of your app without problem?
