### ISSUE TITLE
Text wrap

### ISSUE THREAD

**Issue by cargallo** [lucasferreira/react-native-flash-message#47]
Hi, first of all nice component! There's a way to 'word wrap' the text? I upload a photo look that the word ingresa-do is divided! How can I prevent that? Thanks in advance!

![image](https://user-images.githubusercontent.com/13320290/61399651-f8930b80-a8a4-11e9-8c5f-7eaf0d0041c4.png)

**Comment by cargallo** [comment]
> Hi, first of all nice component! There's a way to 'word wrap' the text? I upload a photo look that the word ingresa-do is divided! How can I prevent that? Thanks in advance!
> 
> ![image](https://user-images.githubusercontent.com/13320290/61399651-f8930b80-a8a4-11e9-8c5f-7eaf0d0041c4.png)

**Comment by lucasferreira** [comment]
Hi @cargallo 

We just use a simple `Text` native component, all the text style options and formating are listed here: https://facebook.github.io/react-native/docs/text#style

But I never see anything like your print before, I guess that could be something in you OS/emulator or language behavior.

**Comment by cargallo** [comment]
Ok. I'll check it. Thanks!
