### ISSUE TITLE
Callback on animation complete?

### ISSUE THREAD

**Issue by kensmash** [lucasferreira/react-native-flash-message#48]
Hi, thank you for this awesome component! Just wondering if there is a way to call a function when the message animation is done? (I'd like to be able to trigger an action in my UI when the message hides itself.) Thanks again!!

**Comment by lucasferreira** [comment]
Hi @kensmash,

Yep it's possible just use `onHide` prop:
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L467

Pass a function in this prop and when the message is done that function will be called.

**Comment by kensmash** [comment]
That is awesome, thank you so much!!!
