### ISSUE TITLE
overlaping navigation bar

### ISSUE THREAD

**Issue by herarya** [lucasferreira/react-native-flash-message#5]
hi, i using react-native-navigtaion , flash message overlape navigation bar

**Comment by lucasferreira** [comment]
Hi @herarya 

Could you upload some image to illustrate the problem?

**Comment by guihouchang** [comment]
![image](https://user-images.githubusercontent.com/6902339/61468861-cf5fa180-a9b0-11e9-93ae-929f4b77a246.png)

just like this,  how can i fix it ?

**Comment by guihouchang** [comment]
@lucasferreira  Thanks
