### ISSUE TITLE
Disable on some scenes/components

### ISSUE THREAD

**Issue by nica0012** [lucasferreira/react-native-flash-message#50]
Hi there, 

I see there is a hideMessage method, is there a way to disable the popups from happening on a specific screen?

Scenario: a user is still getting message notifications when they are in the chat.

I am showing the message from App.js, and wishing I could disable it from anywhere.

Cheers.

**Comment by caetius** [comment]
same issue here

**Comment by lucasferreira** [comment]
Hi @nica0012 and @caetius 

I'll look into this issue for a good solution. By now you could made some sort a HoF to enhance the `showMessage` fn to control as your need.

**Comment by lucasferreira** [comment]
Hi @caetius and @nica0012 

In the latest version of our lib, there are a new method exposed on `FlashMessageManager` utility class that can help to disable or enable:

```javascript
import { useEffect } from "react";
import { FlashMessageManager } from "react-native-flash-message";

function OtherScreen() {
  useEffect(() => {
    // disable all messages...
    FlashMessageManager.setDisabled(true);

    // re-enable on dismount of this screen...
    return () => {
      FlashMessageManager.setDisabled(false);
    };
  }, []);

  return (
    ...
  );
}
```
