### ISSUE TITLE
Love this library

### ISSUE THREAD

**Issue by nandorojo** [lucasferreira/react-native-flash-message#52]
Got this up and running and working perfectly in like 30 seconds. Kept me from making it myself. Thanks so much!

One suggestion: it would be nice to add more custom styles, even if it's just a `containerStyle` and `textStyle` prop for `showMessage`.

**Comment by lucasferreira** [comment]
Hi @nandorojo 

You're welcome ;)

About your suggestion it's already possible to do it, look in to the source of FlashMessage.js:
https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L531

So you can pass some props with `showMessage` method:

```js
showMessage({
  message: "Hello",
  titleStyle: { color: 'red' },
  textStyle: { fontSize: 32 },
  style: { padding: 40 }
});
```

**Comment by nandorojo** [comment]
Ah, got it, thanks for clarifying! I didn't see it on the TypeScript declaration (`src/index.d.ts` line 38) or docs. I think it would be a worthwhile addition for others.

Really appreciate the great work!

**Comment by lucasferreira** [comment]
Hi @nandorojo 

I'm not a TS guy so if you know how to proper declarate `style`, `textStyle` and `titleStyle` props in the `src/index.d.ts` file, you're very welcome ;)

**Comment by nandorojo** [comment]
Got it! I see you added it to the TS file, nice :)

One error I see now since updating is that the schema has `message: Message` as opposed to `message: string` in `index.ts` line 58. The current schema requests you to do this:

```js
showMessage({
  message: { message: 'some message' }
}) 
```

However, this breaks it, so I believe the intended type for message should be `string`. I can edit / submit a PR later, unless you were planing on changing the message schema and just haven't edited the JS file yet :)

Let me know!

**Comment by lucasferreira** [comment]
Hi @nandorojo 

That will be awesome, I really don't work with TS, every effort to get this thing better in our lib will be very welcome!

**Comment by lucasferreira** [comment]
Hi @nandorojo 

We'd shipped a new version at NPM with more TS works, can you look at to see if the styles props now are OK?

**Comment by nandorojo** [comment]
Sure thing! I'll test it out
