### ISSUE TITLE
Extra spacing issue in Android

### ISSUE THREAD

**Issue by vikrantnegi** [lucasferreira/react-native-flash-message#53]
Hi,

In android, there is extra spacing on the bottom of the message. Is there any way to fix this?

![screenshot](https://user-images.githubusercontent.com/3294287/65017552-b473c400-d944-11e9-87e9-ed1e20775a10.jpg)

Thanks.

**Comment by lucasferreira** [comment]
Hi @vikrantnegi 

That's weird thing... are you using `message` or `title` attribute in your `showMessage` call?

Could you swap to see if it gets better? Ex: if you are using:

```js
showMessage({
  title: "Simple message",
  type: "info",
 });
```

Change to:

```js
showMessage({
  message: "Simple message",
  type: "info",
 });
```

And vice-versa.

**Comment by vikrantnegi** [comment]
Hi,

I'm using this
```
showMessage({
   message: error,
});
```

and when I try to use `title` I get a warning and no text gets rendered in the message.

```
Warning: Failed prop type: The prop `message.message` is marked as required in `DefaultFlash`, but its value is `undefined`.
```

Even I try to use the normal flash messages without floating there still seems to be the spacing issue.

**Comment by lucasferreira** [comment]
Ok @vikrantnegi 

I've made a simple test with Expo, you could look here: https://snack.expo.io/Sygi5skDH

If you test using the on-line android device we can't detect any "extra" spacing:
![q](https://user-images.githubusercontent.com/234495/65150982-92894880-d9fb-11e9-9c4c-2efe7ab5944f.png)

So I guess that you are facing some "special issue" that's only happens in your setup. What version of Android are you using? Are you testing in device or just in emulator?

**Comment by vikrantnegi** [comment]
@lucasferreira Weird. I just made a fresh react-native CLI project.

Can you clone the below repo and try running it on the Android Emulator?

Issue Reproduction Repo - https://github.com/vikrantnegi/FlashMessageDemo

Preview - 
![Screenshot_1568819878](https://user-images.githubusercontent.com/3294287/65161771-c2fdd080-da55-11e9-82e6-703c2bf2ee98.png)

Android Emulator Specifications - 
<img width="339" alt="Screen Shot 2019-09-18 at 20 47 02" src="https://user-images.githubusercontent.com/3294287/65161630-88943380-da55-11e9-82e8-335720b8353b.png">

**Comment by lucasferreira** [comment]
Hi @vikrantnegi 

I see it now that you are using the "floating" mode. So knowing this I'm able to reproduce your issue and you are *totally right* there are a extra spacing inside bottom of flash message in floating mode.

I will fix that ASAP and warn you to test the new fixed version.

**Comment by lucasferreira** [comment]
@vikrantnegi 

I just published a new version of this lib in NPM, the version is `0.1.14` that fix you issue.

Can you upgrade in your project and test again?

**Comment by vikrantnegi** [comment]
@lucasferreira Thank you so much. The issue seems to be resolved. You can close this issue.
