### ISSUE TITLE
Incorrect type for message prop

### ISSUE THREAD

**Issue by joaovpmamede** [lucasferreira/react-native-flash-message#55]
I don't think the type for [message](https://github.com/lucasferreira/react-native-flash-message/blob/master/src/index.d.ts#L58) is correct...it should be a `string`.

Also the types for `showMessage` only allow for [MessageOptions](https://github.com/lucasferreira/react-native-flash-message/blob/master/src/index.d.ts#L81) but it seems that the method [accepts 3 params](https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L524)

**Comment by lucasferreira** [comment]
Hi @joaovpmamede thanks for all your contrib ;)

I'd accepted your PRs and publish a new version at NPM.
