### ISSUE TITLE
How import my own style type ?

### ISSUE THREAD

**Issue by chassierPA** [lucasferreira/react-native-flash-message#60]
Hello,

I love this library !!! 

I would like if it's possible to import my style for differents type ! 
I would like change the style type of info, success and error whitout each time pass in my showMessage function my own background style 

Do you guys have any idea ?

Thanks

**Comment by lucasferreira** [comment]
Hi @chassierPA 

If your problem it's backgroundColor, you could use the static method `setColorTheme`.

Like this:

```jsx
class App extends React.Component {
  componentDidMount() {
    FlashMessage.setColorTheme({
      black: "#000",
      strange: "purple",
    });
  }
  render() {
    return (
      <View>
        ...
        <FlashMessage />
      </View>
    );
  }
}
```

With that you could create your own backgroundColor themes and use in all your app.

**Comment by chassierPA** [comment]
work for me thanks
