### ISSUE TITLE
Update your Expo SDK to a higher version

### ISSUE THREAD

**Issue by joaovfsousa** [lucasferreira/react-native-flash-message#74]
It's no longer possible to use the EXPO demonstration because its expo SDK is out of date.

**Comment by W1nstar** [comment]
Seconding this. I tried by all means to install the example on a device, but it's impossible. After many days trying I just desisted.
I want to know if the example code runs on my devices and what are events and such.
Thank you.

**Comment by lucasferreira** [comment]
Hi @joaovfsousa and @W1nstar 

Are you trying to test using this link https://expo.io/@lucasferreira/FlashMessagePlayground?

**Comment by W1nstar** [comment]
Yes:

"This project needs an update
This project uses Expo SDK v32.0.0. If you want to open this project, the author will need to update the project's SDK version."

 And I also tried to run the example, to no avail. Had all kinds of problems with nodejs versions, then expo metro not beign able to run, then bundling failing...

The package installs and works right on the app, but it'd be nice to see the demo.

**Comment by lucasferreira** [comment]
Hi @W1nstar and @joaovfsousa 

I've had updated the version of publish expo demo project, so you could try again (with the same link) and that will be OK.

Thanks for the report ;)
