### ISSUE TITLE
Using Switch Navigator

### ISSUE THREAD

**Issue by Brotakuu** [lucasferreira/react-native-flash-message#75]
How would I add global flash messages if my App.js uses switch navigator?

App.js

```
import React from 'react'
import { StyleSheet, Platform, Image, Text, View } from 'react-native'
import { SwitchNavigator } from 'react-navigation'
// import the different screens
import Loading from './Loading'
import SignUp from './SignUp'
import Login from './Login'
import Main from './Main'
// create our app's navigation stack
const App = SwitchNavigator(
  {
    Loading,
    SignUp,
    Login,
    Main
  },
  {
    initialRouteName: 'Loading'
  }
)
export default App
```

I'm also using tab navigator. Do I need to add flash messages for each tab? Or is it possible to add it globally with SwitchNavigator + TabNavigator

**Comment by lucasferreira** [comment]
Hi @Brotakuu 

Just wrap all yours navigators in a <View /> and put the global flash message inside it.

Like this sample: https://snack.expo.io/Hy7Y01Yc7
