### ISSUE TITLE
Invariant Violation : Element type is invalid : expected a string (for build-in components ) or class

### ISSUE THREAD

**Issue by carl0804** [lucasferreira/react-native-flash-message#76]
After add FlashMessage, I got this error 
![image](https://user-images.githubusercontent.com/25131086/68571980-3b55a080-049f-11ea-9219-ffb44925fbfd.png)

--------------------------
```
import {FlashMessage } from 'react-native-flash-message'

class App extends Component {
  render() {
    return (
      <View style={{flex:1}}>
        <View>
             <Text>hello</Text>
        </View>
        <FlashMessage 
          ref="myLocalFlashMessage" 
        />
      </View>
    );
  }
}
```
--------------------------
"react": "16.9.0",
"react-native": "0.61.4",
"react-native-flash-message": "^0.1.15"

**Comment by nandorojo** [comment]
Your import statement should be default, not named.

Change

```
import {FlashMessage } from 'react-native-flash-message'
```

To this:
```
import FlashMessage from 'react-native-flash-message'
```

**Comment by lucasferreira** [comment]
Hi @carl0804,

@nandorojo it's totally right ;)
