### ISSUE TITLE
ShowMessage doesn't works on Xiaomi Redmi 7A, no error messages.

### ISSUE THREAD

**Issue by JulioCVaz** [lucasferreira/react-native-flash-message#77]
ShowMessage doesn't works on Xiaomi Redmi 7A, no error messages.

**Comment by enggardamar** [comment]
how do you fix it ?

**Comment by JulioCVaz** [comment]
Hello @enggardamar .

So, was actually implementing it incorrectly.

Check you was implementing correctly.
