### ISSUE TITLE
zIndex Issue when propmted in a modal

### ISSUE THREAD

**Issue by veyselkoru** [lucasferreira/react-native-flash-message#83]
![Simulator Screen Shot - iPhone 11 - 2020-02-12 at 11 09 30](https://user-images.githubusercontent.com/5492571/74315297-2e8b6600-4d88-11ea-8b34-aff7a54fab57.png)
React-Native_Modal always front of this.

**Comment by lucasferreira** [comment]
Hi @veyselkoru 

RN Modal works on other native layer that we can't reach using just JavaScript.

A possible solution is [here](https://github.com/lucasferreira/react-native-flash-message/issues/1).

**Comment by enigmablue** [comment]
But the thing is i think I am hoping that the global flash message to even be above the react-native-modal that i'm using. 

Because i have many modals. Having some code that is with ref some without is quite messy. There is no possible solution for global at all?

**Comment by lucasferreira** [comment]
Hi @enigmablue 

Sadly react-native-modal uses RN built-in modal inside: https://github.com/react-native-community/react-native-modal/blob/master/src/modal.tsx#L7

So RN built-in modal solution works on another native View thread that global FlashMessage can't reach =/

**Comment by enigmablue** [comment]
Thanks Lucas,

Do you know if there is another modal that could be used? Not sure if its a stupid question :D
