### ISSUE TITLE
a11n: provide more control over font scaling

### ISSUE THREAD

**Issue by slorber** [lucasferreira/react-native-flash-message#86]
For old users with bigger font sizes (accessibility settings of phone), it is useful to expose the following props for all texts:
- maxFontSizeMultiplier
- allowFontScaling
- minimumFontScale (ios)
- adjustsFontSizeToFit (ios)

These are text props, not style.
This would be more convenient if we could pass a "titleProps" or "descriptionProps", as it would enable to pass custom style (that you would have to merge) + custom props (like the ones I need here).

**Comment by lucasferreira** [comment]
Hi @slorber 

Now it's possible to past `testID` in <FlashMessage /> and other props that you suggest.

Could you test this for us?

Thanks for this issue ;)

**Comment by slorber** [comment]
Hi,

I'm not working on the project needing this anymore, but I guess you can close

**Comment by ngima** [comment]
I was working on one project where I needed to disable font scaling.
I tested by passing textProps and it's working for me to disable font scaling.

```
DefaultFlash.defaultProps = {
    ...DefaultFlash.defaultProps,
    textProps: {
        allowFontScaling: false
    }
};
```

May be it could be helpful for someone.
