### ISSUE TITLE
How to use renderCustomContent

### ISSUE THREAD

**Issue by ismaelbarry** [lucasferreira/react-native-flash-message#88]
Hey all!

I've been playing around for several hours now trying to get the `renderCustomContent` to display a custom view with text. However, I'm not able to get it working. Also, the documentation doesn't provide much information on how to implement it. 

If anyone was able to get this working, how did you do it?

Thanks in advance for the help--really appreciate it!

**Comment by lucasferreira** [comment]
hi @ismaelbarry 

By default, `renderCustomContent` it had to be a function and a prop of `<FlashMessage />` instance.

Something like that:

```jsx
const CustomComponent = () => <View />;

class App extends React.Component {
  ...
  renderCustomContent(message) {
    console.log(message); // if you need to debug what goes around...
    return <CustomComponent message={message} />;
  }
  render() {
    return (
      <View>
        ...
        <FlashMessage renderCustomContent={this.renderCustomContent} />
      </View>
    );
  }
}
```

But there are some open PRs that could change that API in a future...

Did it help?
