### ISSUE TITLE
Use custom icons

### ISSUE THREAD

**Issue by wesleyguirra** [lucasferreira/react-native-flash-message#9]
Hey there, is there any way to use custom icons

**Comment by lucasferreira** [comment]
Hi @wesleyguirra,

I think that is easy to do if you override the default _renderFlashMessageIcon_ method.

I've mad some snack with a demo to you look and help you to achieve that custom icon task: https://snack.expo.io/S13O0OO6f

**Comment by wesleyguirra** [comment]
Hey @lucasferreira Great! it works, thank you!
