### ISSUE TITLE
Message component covers status bar on newer Android phones.

### ISSUE THREAD

**Issue by bartolomej** [lucasferreira/react-native-flash-message#91]
I don't know what I have done wrong.  but I fixed it with this,

<FlashMessage position={ Platform.OS === 'ios' ? "top" : {top:StatusBar.currentHeight, left:0, right:0} }  floating={Platform.OS !== 'ios'}/>

now my App.js looks like this,

```
<Provider store={store}>
  <Container/>
  <FlashMessage position={ Platform.OS === 'ios' ? "top" : {top:StatusBar.currentHeight, left:0, right:0} }  floating={Platform.OS !== 'ios'}/>
</Provider>
```

_Originally posted by @Yasith91 in https://github.com/lucasferreira/react-native-flash-message/issues/29#issuecomment-467332365_

**Above solution fixed the positioning problem, but now the animations don't work correctly.**

This is how the component is positioned before applying above solution (This is the case on newer Android smartphones, that have a low bezel. I'm using Samsung 10e)
![image](https://user-images.githubusercontent.com/36109955/78698911-54099b80-7903-11ea-8fdc-2c5a4af1fd38.png)

This is the expected animation.
![92247054_574949053121545_7884703148135153664_n](https://user-images.githubusercontent.com/36109955/78699632-810a7e00-7904-11ea-8ab5-1c8e916250c1.gif)

This is how the actual animation looks like, when it should be a float in animation.
![92227314_2950726681820880_4845614977026883584_n](https://user-images.githubusercontent.com/36109955/78699260-e90c9480-7903-11ea-904a-c8d214f757be.gif)

**Comment by lucasferreira** [comment]
@bartolomej did you try to move the <FlashMessage /> instance to inside your Container component?

The iOS made all apps "fullscreen" by default, that's why your flash message are shown behind the status bar. Normally everyone had to put some `paddingTop` inside the main root <View /> of an app to solve that OR using some component like SafeAreaView https://reactnative.dev/docs/safeareaview.

**Comment by bartolomej** [comment]
I tried that now, but adding some top "space" to the top of your whole app creates some new problems of its own, because libraries like react-navigation already handle that ([see here](https://reactnavigation.org/docs/handling-safe-area/)).

My root container code looks like this:
```React.js
<Provider store={store}>
  <NavigationContainer>
    <AuthenticationStack/>
    <FlashMessage position="top"/>
  </NavigationContainer>
</Provider>
```

I wrapper my app ui in a `SafeAreaView` like this:
```React.js
<Provider store={store}>
  <NavigationContainer>
    <SafeAreaView style={myCustomStyles}>
      <AuthStack/>
      <FlashMessage position="top"/>
    </SafeAreaView>
  </NavigationContainer>
</Provider>
```
But SafeAreaView doesn't work properly on Android devices with a notch (also mentioned [here](https://stackoverflow.com/questions/51289587/react-native-how-to-use-safeareaview-for-android-notch-devices/55017347)) and applying custom styles with "paddingTop" to SafeAreaView, caused my app to display a blank screen.

Below solution works, but now i have extra space up top because I'm using react-navigation, so i think it would be best if this was handled by the library itself.
```React.js
export default function () {
  const appContainerStyles = Platform.OS === 'android' ? {
    height: Dimensions.get('window').height,
    width: '100%',
    position: 'absolute',
    bottom: 0
  } : {};
  return (
    <Provider store={store}>
      <NavigationContainer>
        <SafeAreaView style={appContainerStyles}>
          <AuthStack/>
          <FlashMessage position="top"/>
        </SafeAreaView>
      </NavigationContainer>
    </Provider>
  )
}
```

**Comment by lucasferreira** [comment]
The FlashMessage component did a lot of "status bar height calcs" as you could see here:
https://github.com/lucasferreira/react-native-flash-message/blob/71a2f697f96adbf86a13fabdf3b043a06b7bd99c/src/FlashMessageWrapper.js#L59

So I think the problem it's only with some kind of androids device (as you report). You said that are using Samsung 10e, what version of Android OS?

**Comment by bartolomej** [comment]
Oh i see. The phone is running Android 10 with Samsung's One UI 2.1. Well I see there really isn't much we can do to solve this, but I will try and test if that behaviour is seen on other similar phones.

**Comment by damithg-dev** [comment]
Any solution to this? Having issues on Samsung m21 and note 9 running on the latest one UI.

**Comment by lucasferreira** [comment]
Hi @damithg-dev 

Apparently One UI has some problems with React Native dimensions (and other calcs) as we can se here
https://github.com/facebook/react-native/issues/30638

I do not have access to any of this devices to test if I find some workaround, but if you find some way to fix this using your devices in process, please feel welcome to send us a PR.
