### ISSUE TITLE
renderFlashMessageIcon Custom props

### ISSUE THREAD

**Issue by velcis** [lucasferreira/react-native-flash-message#92]
Hello, i check this expo demo https://snack.expo.io/SyOmzEUxI to custom flashMessageIcon, but i cant achieve with CUSTOM PROPS, i need to send and avatar <Image> to user like a chat, but i cant send it as a props.

**Comment by lucasferreira** [comment]
Hi @velcis in the lastest version now this is possible, you can pass renderFlashMessageIcon as a showMessage prop, sorry for this long delay ;)
