### ISSUE TITLE
Can't click while message is showing

### ISSUE THREAD

**Issue by karimcambridge** [lucasferreira/react-native-flash-message#93]
Are we not supposed to be able to click other parts of the screen whilst a flash message is showing?

Not sure what's happening

```js

			showMessage({
				position: 'center',
				message: 'Driving mode on.',
				description: 'You will now receive rider requests.',
				backgroundColor: '#DDDDDD',
				icon: 'success',
				duration: 3000,
				floating: true,
			});

**Comment by lucasferreira** [comment]
Hi @karimcambridge,

When you use the "position=center" this View:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L567

Will be placed all over your apps, it's like a "transparent" rootView that have the FlashMessage centered inside. So I guess that this "transparent" rootView are blocking the rest of your app.

I suggest to you use other position like top, just to test this case.
