### ISSUE TITLE
Change style of message wrapper 

### ISSUE THREAD

**Issue by ThomasCarca** [lucasferreira/react-native-flash-message#94]
Hello, thanks for you for the cool library !

I was wondering if there was a way to modify the style of the View wrapping the message.
To be more specific, I would like to change the opacity of the View behind the message when is is displayed.

For now, I'm doing this : 

```
import { Dimensions, StyleSheet, View, ViewProps } from 'react-native';
import React from 'react';
import { showMessage } from 'react-native-flash-message';
import { Colors } from '~assets/styles';

interface AlertInterface extends ViewProps {
  type: 'none' | 'default' | 'info' | 'success' | 'danger' | 'warning' | undefined;
  title: string;
  description: string;
  onPress: () => void;
}

const { height, width } = Dimensions.get('screen');

const Alert = ({ type, title, description, onPress }: AlertInterface) => {
  React.useEffect(() => {
    showMessage({
      message: title,
      description,
      type,
      position: 'center',
      autoHide: false,
      onPress,
    });
  }, [description, onPress, title, type]);

  return <View style={[styles.overlay, styles.mediumOpacity]} />;
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    position: 'absolute',
    left: 0,
    top: 0,
    width: width,
    height: height,
  },
  mediumOpacity: {
    opacity: 0.6,
    backgroundColor: Colors.black,
  },
});

export default Alert;
```

... and then invoke the Alert component when I need the message to be displayed. 

I don't really like this approach as I think I should not need to add a View each time I need to display a message.

**Comment by lucasferreira** [comment]
Hi @ThomasCarca 

Sorry for the delayed return, but I think you need to custom this View here:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L567

Nowadays it isn't possible, sorry. I could look for some style props like `rootStyle` or something that will be passed from `<FlashMessage />` but I don't know when this will happening (future releases).

So if u need this ASAP you can send us some PR with this modification ;)
