### ISSUE TITLE
Message Covers Bottom Navigation Tabs

### ISSUE THREAD

**Issue by chriscom2019** [lucasferreira/react-native-flash-message#96]
Im using this component to display form validation errors in three different screens in material-top-tabs navigator. The global implementation works fine for me but the challenge is, the message is covering the tabs from the bottom. If I use local implementation the message is not showing in the currently active tab screen instead it is shows the last tab screen. Please assists

**Comment by lucasferreira** [comment]
Hi @chriscom2019 

The component was written like a modal, to cover all the app, always above everything.
