### ISSUE TITLE
Support for accessibility (and more props in MessageComponent)

### ISSUE THREAD

**Issue by Masadow** [lucasferreira/react-native-flash-message#97]
It would be great to be able to set accessibility.

For now, I can get a workaround by either implementing a custom MessageComponent or using : 

```ts
// @ts-ignore
DefaultFlash.defaultProps = {
  accessible: true,
  testId: 'myLabel',
  accessibilityLabel: 'myLabel',
  // @ts-ignore
  ...DefaultFlash.defaultProps
};
```

However this is not ideal as I can't have a different accessibility label for different alerts easily.

This should be quite easy to implement as it's just a prop to pass to DefaultFlash. By the way, it would be great for FlashMessage component to pass all of its rest props to MessageComponent ;)

**Comment by lucasferreira** [comment]
Hi @Masadow 

Now in the lastest version of this package you could pass some accessibility props in default <FlashMessage /> instance:

https://github.com/lucasferreira/react-native-flash-message/blob/master/src/FlashMessage.js#L562

What do you think?
