### ISSUE TITLE
Calling hideMessage() make message impossible to show again. 

### ISSUE THREAD

**Issue by rdhox** [lucasferreira/react-native-flash-message#98]
Great lib :) Here my code:

```js
  ...
  const [ isInternetOn, setIsInternetOn ] = useState<boolean>(true);
  
  useEffect(() => {
    async function isOnlineAtStart() {
      const online: boolean = await isConnectedToInternet(); 
      setIsInternetOn(online);
    }
    const unsubNetInfo = NetInfo.addEventListener(({isConnected, isInternetReachable}) => {
      if(isConnected && isInternetReachable) {
        setIsInternetOn(true);
      } else {
        setIsInternetOn(false);
      }
    });
    isOnlineAtStart();
    return () => {
      unsubNetInfo();
    };
  }, []);

  useEffect(() => {
    if(!isInternetOn) {
      showMessage({
        message: 'You need to have an internet access to ...',
        type: "warning",
        autoHide: false,
        color: "white"
      });
    } else {
      hideMessage();
    }
  }, [isInternetOn]);
```

I just want to show a warning message when the connection is lost, and to remove the message when the connection is on. But calling hideMessage() once seems to cancel the possibility to show a message after the call. If I remove the `else { hideMessage()}`, and I simulate a connection off and back online, the message show but doesn't disappear.

Is there a possibility to do something like:

```js
  useEffect(() => {
    if(!isInternetOn) {
      showMessage({
        message: 'You need to have an internet access to ...',
        type: "warning",
        autoHide: false,
        color: "white"
      });
    } else {
      if(messageDisplayed) {
        hideMessage();
     }
    }
  }, [isInternetOn]);
```

Is there something I'm missing? 

thanks!

**Comment by lucasferreira** [comment]
Hi @rdhox

Did you tried to put some `console.log` near by your `hideMessage()` call to see if it this method aren't keep called forever?

**Comment by rdhox** [comment]
Thank for your answer @lucasferreira. Yes I checked that possibility and it's working fine, no repetitive calls here.

**Comment by rdhox** [comment]
I made a snack to simulate the bug:

https://snack.expo.io/@rdhox/bug-react-native-flash-message

And it's working perfectly... I will investigate my project to see why it's not working inside it. Guess we can close the issue?

**Comment by lucasferreira** [comment]
Hi @rdhox 

You made exactly what I would do to test if it our component (FlashMessage) could work on this scenario, simulate the toggle of `isInternetOn` proves that FlashMessage can be shown several times.

Thanks for your expo snack and I will close this issue for now ;)
